insert into sections (section_name,class_adviser,grade) values ('Aether','T0001',10);
insert into sections (section_name,class_adviser,grade) values ('Uranium','T0002', 10);
insert into sections (section_name,class_adviser,grade) values ('Faith', 'T0003',8);
insert into sections (section_name,class_adviser,grade) values ('Infinity','T0004', 10);
insert into sections (section_name,class_adviser,grade) values ('Lead', 'T0005',8);
insert into sections (section_name,class_adviser,grade) values ('Integrity', 'T0006',8);
insert into sections (section_name,class_adviser,grade) values ('Ragnarok', 'T0007',9);
insert into sections (section_name,class_adviser,grade) values ('Loki', 'T0008',9);
insert into sections (section_name,class_adviser,grade) values ('Socrates', 'T0009',7);
insert into sections (section_name,class_adviser,grade) values ('Plato', 'T0010',7);
insert into sections (section_name,class_adviser,grade) values ('Aristotle', 'T0011',7);
insert into sections (section_name,class_adviser,grade) values ('Tony', 'T0012',9);
