insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00001', 'Ashlie', 'Romi', 13, '9536 Buena Vista Hill', 'Polygender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00002', 'Wendy', 'Roffe', 11, '19 Farragut Place', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00003', 'Niels', 'Topping', 13, '50 Graceland Parkway', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00004', 'Clive', 'Blowing', 15, '433 International Center', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00005', 'Oriana', 'Demangeot', 12, '61 Dennis Pass', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00006', 'Laverne', 'Itzik', 14, '3 Charing Cross Parkway', 'Polygender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00007', 'Yuri', 'Shatford', 11, '08 Warrior Point', 'Male', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00008', 'Shirleen', 'Halahan', 16, '9468 Butternut Court', 'Non-binary', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00009', 'Kerk', 'Mansford', 15, '067 Packers Trail', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00010', 'Cooper', 'Fairlaw', 15, '8512 East Park', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00011', 'Andriette', 'Gillbey', 12, '42 Muir Junction', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00012', 'Sandi', 'Lailey', 16, '66490 Lien Point', 'Female', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00013', 'Sher', 'Elies', 16, '7409 Moland Center', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00014', 'Raimundo', 'Nottram', 12, '940 Northland Way', 'Genderqueer', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00015', 'Ilsa', 'MacKimmie', 15, '0 Southridge Lane', 'Bigender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00016', 'Cybill', 'Bonifant', 12, '1 Blackbird Alley', 'Non-binary', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00017', 'Halie', 'Tabner', 14, '96 Packers Drive', 'Bigender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00018', 'Iver', 'Itzkowicz', 16, '287 Blue Bill Park Parkway', 'Genderfluid', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00019', 'Glyn', 'Comfort', 12, '483 Arkansas Road', 'Non-binary', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00020', 'Gaspar', 'Reolfo', 15, '639 Farragut Trail', 'Agender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00021', 'Morgan', 'Dober', 11, '29435 Stang Junction', 'Female', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00022', 'Dre', 'Mc Trusty', 13, '65 Warbler Street', 'Bigender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00023', 'Park', 'Oddie', 14, '01 Morning Road', 'Agender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00024', 'Genia', 'Redsall', 13, '986 Bellgrove Road', 'Agender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00025', 'Gilbertina', 'Mursell', 13, '4 Mosinee Court', 'Genderfluid', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00026', 'Janette', 'Seabridge', 12, '8835 Monument Way', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00027', 'Barnebas', 'Britton', 12, '6 Oriole Street', 'Polygender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00028', 'Naoma', 'Doogan', 12, '13 Birchwood Place', 'Genderfluid', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00029', 'Ira', 'Matveichev', 14, '7 Anthes Point', 'Bigender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00030', 'Lock', 'Lathee', 16, '666 Monterey Avenue', 'Non-binary', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00031', 'Beverlie', 'Como', 16, '0477 Mayfield Alley', 'Agender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00032', 'Hedwiga', 'Valadez', 11, '2 Northwestern Plaza', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00033', 'Evvy', 'Dewdney', 14, '3 Rieder Place', 'Polygender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00034', 'Jammal', 'Sherrington', 14, '7913 Gina Hill', 'Agender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00035', 'Lauritz', 'Callacher', 13, '30 Old Gate Place', 'Non-binary', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00036', 'Dun', 'Bouette', 11, '58 Dovetail Place', 'Bigender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00037', 'Martainn', 'Tams', 16, '007 Chinook Trail', 'Female', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00038', 'Valentin', 'Donne', 16, '73341 Anniversary Hill', 'Non-binary', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00039', 'Janella', 'Caulket', 14, '68451 Shoshone Plaza', 'Genderfluid', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00040', 'Thacher', 'Joncic', 15, '883 Pierstorff Place', 'Agender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00041', 'Veronica', 'Van Zon', 14, '696 Mallory Street', 'Female', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00042', 'Farly', 'Pimlock', 13, '24 Scott Court', 'Female', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00043', 'Gilligan', 'Charnley', 12, '9 Eggendart Trail', 'Bigender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00044', 'Ody', 'Schout', 13, '2 Algoma Drive', 'Genderqueer', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00045', 'Marlow', 'Mawby', 15, '77709 Cambridge Trail', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00046', 'Kathie', 'Lamar', 15, '76 La Follette Terrace', 'Non-binary', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00047', 'Woodrow', 'Felgate', 11, '28 Vernon Center', 'Male', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00048', 'Aldrich', 'Mayte', 12, '07 Huxley Crossing', 'Male', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00049', 'Matthias', 'Laddle', 16, '345 Fisk Alley', 'Female', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00050', 'Aloisia', 'Enns', 14, '695 Chive Junction', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00051', 'Leonard', 'Drinkwater', 11, '3 Acker Center', 'Bigender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00052', 'Maire', 'Metcalfe', 11, '0 Weeping Birch Parkway', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00053', 'Tremain', 'Jacombs', 15, '8 Shopko Drive', 'Polygender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00054', 'Mendie', 'Robeson', 11, '5109 Green Ridge Way', 'Female', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00055', 'Rozalin', 'Sindell', 11, '34948 Ohio Place', 'Non-binary', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00056', 'Fidela', 'Hargreaves', 16, '55 Melby Hill', 'Agender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00057', 'Justinian', 'Birt', 12, '3230 Burrows Parkway', 'Genderqueer', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00058', 'Rebecka', 'Sholl', 11, '17 Menomonie Circle', 'Female', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00059', 'Rowney', 'Markham', 12, '155 Saint Paul Drive', 'Polygender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00060', 'Fredek', 'Rosendale', 15, '544 Dwight Alley', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00061', 'Glennis', 'Jochanany', 13, '7478 Ramsey Way', 'Bigender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00062', 'Mylo', 'Wiltshier', 13, '4 Burrows Street', 'Bigender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00063', 'Zorah', 'Loftus', 15, '5334 Mcbride Terrace', 'Male', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00064', 'Valry', 'Kassel', 12, '7 Calypso Alley', 'Bigender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00065', 'Dory', 'Mellows', 11, '0554 Redwing Drive', 'Genderqueer', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00066', 'Betsey', 'Fowler', 12, '26 Bluejay Lane', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00067', 'Pietra', 'Hindsberg', 16, '75566 Center Trail', 'Female', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00068', 'Kitti', 'Dadds', 16, '24 Fremont Hill', 'Polygender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00069', 'Anastasie', 'Keyworth', 11, '0 Emmet Lane', 'Polygender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00070', 'Joelie', 'Zanetto', 12, '00 Hauk Junction', 'Male', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00071', 'Edee', 'Warcop', 14, '68 Lakewood Gardens Avenue', 'Agender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00072', 'Tailor', 'Alliband', 16, '8 Scofield Lane', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00073', 'Yul', 'Shearmer', 13, '94192 Schurz Hill', 'Non-binary', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00074', 'Marin', 'Tiron', 16, '91 Schmedeman Terrace', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00075', 'Anatola', 'Biscomb', 14, '3859 Pepper Wood Drive', 'Bigender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00076', 'Arleta', 'Facer', 15, '1 Sloan Point', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00077', 'Bram', 'Vaskin', 12, '7 Quincy Hill', 'Bigender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00078', 'Agace', 'Riddel', 14, '6012 Westport Terrace', 'Non-binary', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00079', 'Lauree', 'Cutcliffe', 14, '508 Rieder Avenue', 'Male', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00080', 'Ada', 'Dowzell', 14, '3715 Summer Ridge Crossing', 'Female', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00081', 'Kelci', 'Druhan', 15, '06447 Coolidge Alley', 'Agender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00082', 'Pincas', 'Cammidge', 13, '6659 Barnett Street', 'Agender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00083', 'Jada', 'Tockell', 16, '501 Bunting Point', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00084', 'Lyman', 'Jerke', 12, '23 Clemons Alley', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00085', 'Monte', 'Dennis', 11, '78 Fair Oaks Place', 'Polygender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00086', 'Neda', 'Rusbridge', 11, '019 Green Place', 'Genderqueer', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00087', 'Barnabas', 'Speechley', 12, '936 Ludington Park', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00088', 'Chancey', 'Kimbrough', 13, '431 Duke Road', 'Polygender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00089', 'Dion', 'Le Batteur', 16, '910 Gateway Point', 'Genderfluid', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00090', 'Yul', 'Skep', 16, '0001 Lakewood Plaza', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00091', 'Karlik', 'Larroway', 14, '001 Ramsey Trail', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00092', 'Thomasine', 'Depka', 14, '3687 Dwight Hill', 'Bigender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00093', 'Stavro', 'Zannini', 11, '86956 Grover Circle', 'Genderfluid', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00094', 'Lexine', 'Champkin', 14, '4 Mesta Center', 'Non-binary', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00095', 'Shayne', 'Knoles', 15, '79976 Petterle Plaza', 'Male', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00096', 'Stavro', 'Whitney', 16, '15542 Mcbride Alley', 'Female', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00097', 'Euphemia', 'Elmhirst', 15, '70 Birchwood Place', 'Genderfluid', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00098', 'Alfredo', 'Sibbs', 12, '761 Nelson Avenue', 'Non-binary', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00099', 'Hector', 'Domniney', 16, '304 Independence Avenue', 'Female', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00100', 'Giavani', 'Letixier', 16, '891 Kim Avenue', 'Bigender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00101', 'Mead', 'Duffield', 11, '7051 Stang Parkway', 'Agender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00102', 'Curtis', 'Bache', 15, '6315 Tennyson Place', 'Agender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00103', 'Peadar', 'Bathowe', 11, '55 1st Park', 'Male', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00104', 'Michel', 'Vossgen', 12, '781 Green Ridge Terrace', 'Male', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00105', 'Nancey', 'Farraway', 14, '3 Porter Lane', 'Genderfluid', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00106', 'Nissie', 'Bende', 11, '17 Elgar Pass', 'Non-binary', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00107', 'Cortie', 'Coule', 13, '0 8th Junction', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00108', 'Che', 'Vernay', 14, '95 Pine View Parkway', 'Polygender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00109', 'Fanny', 'Epgrave', 13, '04 Artisan Park', 'Male', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00110', 'Bentley', 'Espinoy', 12, '093 Chive Court', 'Genderfluid', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00111', 'Trudi', 'Crisp', 14, '8847 Jenifer Court', 'Agender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00112', 'Arden', 'Brough', 11, '24070 Meadow Valley Drive', 'Genderqueer', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00113', 'Nappy', 'Gosenell', 15, '035 Granby Trail', 'Non-binary', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00114', 'Donica', 'Boggers', 13, '36926 Paget Way', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00115', 'Karola', 'Daine', 11, '573 Di Loreto Point', 'Genderqueer', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00116', 'Hermie', 'Pavkovic', 11, '621 Harbort Street', 'Non-binary', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00117', 'Ewen', 'MacKibbon', 12, '85 Parkside Point', 'Male', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00118', 'Andrea', 'Gallagher', 11, '6 Fisk Parkway', 'Genderfluid', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00119', 'Chloe', 'Giannazzi', 16, '8 Iowa Street', 'Male', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00120', 'Edan', 'Neeves', 16, '98727 Mariners Cove Lane', 'Polygender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00121', 'Biddie', 'Johl', 15, '3767 Crownhardt Plaza', 'Polygender', 7);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00122', 'Helyn', 'Huntingford', 13, '3556 Pond Lane', 'Polygender', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00123', 'Preston', 'Gillam', 16, '99629 Corry Terrace', 'Bigender', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00124', 'Ruthy', 'Stithe', 16, '96 Eagan Way', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00125', 'Haleigh', 'Degenhardt', 14, '6185 Lighthouse Bay Court', 'Male', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00126', 'Drusi', 'Ilyenko', 12, '870 Norway Maple Center', 'Female', 10);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00127', 'Cordey', 'Gosswell', 15, '455 Birchwood Way', 'Non-binary', 9);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00128', 'Vivi', 'Andreone', 15, '59 Rusk Park', 'Agender', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00129', 'Minnnie', 'Lamberton', 15, '00 Sommers Lane', 'Genderqueer', 8);
insert into students (student_id, first_name, middle_initial, age, address, gender, grade_level) values ('S00130', 'Faye', 'Hammon', 13, '628 Sherman Alley', 'Genderqueer', 9);
