insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00001', 'Briant', 'Clogg', 'Ding', 'Female', '46 High Crossing Pass', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00002', 'Baillie', 'Georgescu', 'Parradine', 'Male', '7031 Fuller Road', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00003', 'Josephine', 'Brokenbrow', 'Busfield', 'Female', '15383 American Ash Street', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00004', 'Taddeusz', 'Schirok', 'Harpur', 'Female', '8 John Wall Street', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00005', 'Claybourne', 'Quested', 'Orringe', 'Genderfluid', '0631 Dunning Avenue', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00006', 'Alanson', 'Trembey', 'Frodsam', 'Genderfluid', '69828 Logan Parkway', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00007', 'Raphaela', 'Shorland', 'Andriuzzi', 'Bigender', '55 Londonderry Crossing', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00008', 'Filippa', 'Fisbey', 'Beaconsall', 'Non-binary', '4 Portage Alley', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00009', 'Karlik', 'Winslett', 'Cuffin', 'Male', '2 Roxbury Avenue', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00010', 'Gusella', 'Rottger', 'Milbourne', 'Female', '37 Kipling Plaza', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00011', 'Richmond', 'MacTerrelly', 'Tallant', 'Female', '6091 Lotheville Court', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00012', 'Earle', 'Farrah', 'Kinglake', 'Bigender', '8 Oak Drive', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00013', 'Cloe', 'Sherlaw', 'Francecione', 'Male', '65175 Mandrake Crossing', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00014', 'Beitris', 'Sandison', 'Yakobowitz', 'Bigender', '13 Vera Court', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00015', 'Brunhilda', 'Jori', 'Jorgesen', 'Genderfluid', '70 Walton Hill', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00016', 'Danella', 'Blacklock', 'Capeling', 'Bigender', '4 Randy Point', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00017', 'Katuscha', 'Victoria', 'Schettini', 'Agender', '9 Farwell Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00018', 'Kinsley', 'Crosscombe', 'McNally', 'Female', '364 David Way', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00019', 'Chaunce', 'Alvy', 'Ledbetter', 'Non-binary', '0 Eastwood Circle', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00020', 'Mallory', 'Burdett', 'Wogden', 'Male', '0 Moose Avenue', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00021', 'Orran', 'Dell ''Orto', 'Manton', 'Bigender', '40 Derek Street', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00022', 'Trudey', 'Maplestone', 'Richardin', 'Polygender', '87 Loomis Lane', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00023', 'Laryssa', 'Hartzenberg', 'McAuslene', 'Male', '611 Comanche Road', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00024', 'Sib', 'Daelman', 'Silcocks', 'Male', '5418 Carioca Center', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00025', 'Sabina', 'Kilbourn', 'Legion', 'Agender', '19607 Luster Parkway', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00026', 'Jervis', 'Wagge', 'Burchill', 'Genderqueer', '34249 International Hill', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00027', 'Gleda', 'Burkert', 'Ferreras', 'Genderfluid', '8060 Blaine Hill', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00028', 'Guillemette', 'Peschke', 'Spenclay', 'Female', '2393 Lakewood Gardens Place', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00029', 'Farrell', 'Jehan', 'Gronw', 'Bigender', '8 Scoville Avenue', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00030', 'Gaile', 'Geane', 'Simeons', 'Female', '2888 Esch Alley', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00031', 'Tersina', 'Mingardo', 'Jacqueme', 'Female', '84 Rockefeller Junction', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00032', 'Rodge', 'Mc Menamin', 'Dehm', 'Agender', '647 Clarendon Avenue', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00033', 'Alidia', 'Bilbie', 'McNess', 'Genderfluid', '8 Sullivan Plaza', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00034', 'Augusta', 'Wingar', 'Waiton', 'Genderfluid', '148 Mitchell Lane', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00035', 'Giraldo', 'Grzesiewicz', 'Matteotti', 'Non-binary', '61054 Farmco Park', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00036', 'Vitia', 'Hatje', 'Natt', 'Female', '24 Dovetail Lane', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00037', 'Butch', 'Minmagh', 'Cressar', 'Genderfluid', '78 High Crossing Park', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00038', 'Ariela', 'Wink', 'Waleran', 'Male', '34680 Dapin Drive', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00039', 'Kass', 'Petrollo', 'Wardlaw', 'Genderqueer', '7 Holmberg Point', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00040', 'Cross', 'Milsap', 'Norval', 'Male', '57 Paget Trail', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00041', 'Xymenes', 'Hearle', 'Faldo', 'Male', '93 Norway Maple Trail', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00042', 'Collen', 'Osbaldeston', 'Gercke', 'Genderfluid', '610 Pearson Pass', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00043', 'Marin', 'Bavister', 'Streader', 'Genderfluid', '59 Mallard Parkway', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00044', 'Bruno', 'Emberton', 'Blankley', 'Bigender', '20055 Monument Terrace', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00045', 'Tiffi', 'Ogus', 'Divisek', 'Non-binary', '762 Manufacturers Terrace', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00046', 'Howey', 'Harflete', 'Tzar', 'Bigender', '2 5th Crossing', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00047', 'Tiffie', 'Trunkfield', 'Chadd', 'Female', '93 Michigan Park', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00048', 'Robby', 'Furst', 'Willgrass', 'Bigender', '7 Clarendon Lane', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00049', 'Flory', 'Druett', 'Cardenosa', 'Genderqueer', '459 Crownhardt Terrace', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00050', 'Geordie', 'MacCleay', 'McKoy', 'Female', '94855 Steensland Parkway', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00051', 'Wallie', 'Curnnok', 'Rustedge', 'Polygender', '03375 North Hill', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00052', 'Harlan', 'Alvar', 'Zuan', 'Male', '9 Magdeline Park', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00053', 'Joana', 'Bowton', 'Branney', 'Agender', '5 Magdeline Plaza', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00054', 'Irvin', 'Dadson', 'Hirtz', 'Agender', '79319 Columbus Road', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00055', 'Alisha', 'Fryer', 'Yushmanov', 'Female', '96684 Golf Course Circle', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00056', 'Luis', 'Eliassen', 'Frisdick', 'Male', '95787 Stephen Street', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00057', 'Cosme', 'McMichell', 'Makeswell', 'Non-binary', '87 Eagan Point', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00058', 'Tyler', 'Harman', 'Hark', 'Bigender', '7894 Maple Wood Street', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00059', 'Demetra', 'Esel', 'Blaydon', 'Bigender', '6 Southridge Avenue', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00060', 'Wendall', 'Denyukin', 'Rasmus', 'Female', '69425 Maryland Park', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00061', 'Ernestine', 'Ferronel', 'Maken', 'Female', '272 Waubesa Center', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00062', 'Avictor', 'Palay', 'Trowsdall', 'Genderfluid', '927 Pierstorff Crossing', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00063', 'Clim', 'McIlmurray', 'Eagar', 'Polygender', '54 Melby Hill', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00064', 'Jillie', 'Bachshell', 'Cote', 'Polygender', '575 Hansons Lane', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00065', 'Obediah', 'Hestrop', 'Dellatorre', 'Genderfluid', '967 Jay Plaza', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00066', 'Lauree', 'Gallie', 'Melchior', 'Non-binary', '4962 Golf View Avenue', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00067', 'Jacklin', 'Benard', 'Dymoke', 'Genderfluid', '55132 Elka Center', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00068', 'Maxie', 'Charlot', 'Brookz', 'Male', '248 West Circle', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00069', 'Quinn', 'O''Cannon', 'Trevino', 'Male', '44431 Buena Vista Trail', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00070', 'Saxon', 'Halburton', 'Simister', 'Bigender', '4 Drewry Court', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00071', 'Tillie', 'Pilkinton', 'Sproule', 'Agender', '46 Ruskin Terrace', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00072', 'Joey', 'Pepi', 'Darrington', 'Non-binary', '3425 Garrison Pass', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00073', 'Fiona', 'Mayte', 'Bidwell', 'Polygender', '349 Weeping Birch Pass', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00074', 'Alic', 'Blannin', 'Orringe', 'Agender', '5 Hermina Road', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00075', 'Ardis', 'Weaben', 'Akeherst', 'Genderqueer', '85963 Forest Pass', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00076', 'Mallissa', 'Burder', 'Hankins', 'Female', '7 Twin Pines Circle', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00077', 'Sonnnie', 'Eixenberger', 'May', 'Agender', '0 Bunting Avenue', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00078', 'Pippa', 'Templman', 'MacColl', 'Bigender', '51461 Lindbergh Circle', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00079', 'Myra', 'Grahlmans', 'Trevallion', 'Polygender', '96613 Texas Lane', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00080', 'Annadiana', 'Hedditeh', 'Cosyns', 'Agender', '78 Pine View Hill', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00081', 'Wynn', 'Crawford', 'Oldcote', 'Male', '42 Butterfield Place', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00082', 'Lela', 'Greschke', 'Mozzetti', 'Non-binary', '03180 Stone Corner Plaza', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00083', 'Shaun', 'Tupling', 'Bernini', 'Bigender', '38 Veith Junction', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00084', 'Elaine', 'Jorden', 'Telfer', 'Genderfluid', '1 Fulton Junction', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00085', 'Enrica', 'Aris', 'McKiernan', 'Genderqueer', '97 Merry Plaza', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00086', 'Georgina', 'Waslin', 'von Hagt', 'Male', '0 Hallows Terrace', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00087', 'Dannye', 'Pesic', 'Derill', 'Genderfluid', '86874 Northview Place', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00088', 'Dawna', 'Tick', 'Hoodspeth', 'Genderfluid', '857 Maple Wood Avenue', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00089', 'Iain', 'Germann', 'Behling', 'Genderqueer', '5904 2nd Crossing', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00090', 'Leena', 'Rambaut', 'Rielly', 'Female', '16744 Hanson Park', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00091', 'Emilee', 'Antoniades', 'Macallam', 'Female', '37 Knutson Junction', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00092', 'Staford', 'Eakley', 'Pinwell', 'Female', '6 Monica Point', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00093', 'Gustav', 'Tozer', 'Ilett', 'Bigender', '33 Anniversary Plaza', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00094', 'Katharine', 'McArthur', 'Veel', 'Bigender', '835 Dawn Road', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00095', 'Alisha', 'Krale', 'Armsden', 'Female', '500 Anzinger Street', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00096', 'Haydon', 'Dimbleby', 'Cauderlie', 'Bigender', '3 Walton Junction', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00097', 'Thea', 'Elion', 'Debnam', 'Bigender', '632 Forest Road', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00098', 'Audry', 'Jeffery', 'Durber', 'Non-binary', '1 Kenwood Terrace', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00099', 'Weylin', 'Mainston', 'Philp', 'Polygender', '75227 Clyde Gallagher Circle', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00100', 'Katerine', 'Palley', 'Andriolli', 'Genderqueer', '26690 Northfield Alley', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00101', 'Lesley', 'Bartoszewski', 'Llorente', 'Polygender', '49233 Emmet Terrace', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00102', 'Wendye', 'Hardan', 'Veevers', 'Bigender', '6 Hansons Lane', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00103', 'Myrna', 'Evenden', 'Culshew', 'Bigender', '9 Crownhardt Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00104', 'Bink', 'Wick', 'McClarence', 'Genderfluid', '10930 Wayridge Alley', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00105', 'Sara', 'Roder', 'Hubball', 'Genderfluid', '26 Jay Alley', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00106', 'Rudolfo', 'Craske', 'Featonby', 'Agender', '57821 Petterle Place', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00107', 'Jeniece', 'Faireclough', 'Cadogan', 'Genderqueer', '05537 Gina Circle', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00108', 'Jayne', 'Nisot', 'Jakolevitch', 'Polygender', '520 Oriole Plaza', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00109', 'Chadwick', 'Coley', 'Richards', 'Genderqueer', '3075 Upham Crossing', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00110', 'Antonius', 'Khilkov', 'Wolfers', 'Female', '074 Pleasure Plaza', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00111', 'Gunter', 'Mayers', 'Malzard', 'Male', '7309 Washington Plaza', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00112', 'Margi', 'Hlavac', 'Laviss', 'Agender', '45659 Gulseth Point', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00113', 'Clio', 'Murt', 'Iorizzo', 'Genderqueer', '82 Blackbird Avenue', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00114', 'Janelle', 'Suttie', 'Dawid', 'Agender', '376 Saint Paul Hill', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00115', 'Clo', 'Tours', 'Lysaght', 'Genderqueer', '9 Twin Pines Center', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00116', 'Annabela', 'Montague', 'Dodle', 'Genderqueer', '06532 Kipling Terrace', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00117', 'Fanchon', 'Smy', 'Turton', 'Genderqueer', '89538 Stoughton Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00118', 'Amye', 'Behrend', 'Bartlett', 'Genderfluid', '3754 Loeprich Hill', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00119', 'North', 'Lytle', 'Stolli', 'Non-binary', '1362 Grayhawk Drive', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00120', 'Barbaraanne', 'Concklin', 'Reubel', 'Male', '49 Fair Oaks Crossing', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00121', 'Carmela', 'Presidey', 'Feldmus', 'Polygender', '784 Milwaukee Pass', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00122', 'Astrix', 'Seale', 'Wratten', 'Genderfluid', '8288 Sage Plaza', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00123', 'Lorianne', 'Farrant', 'Shaddick', 'Female', '73 Hoffman Court', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00124', 'Leilah', 'Batisse', 'Nelles', 'Male', '70589 Acker Circle', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00125', 'Nappy', 'Bern', 'Bygraves', 'Bigender', '9 Westport Center', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00126', 'Gibby', 'Liven', 'Ginity', 'Genderfluid', '5 Macpherson Pass', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00127', 'Stanwood', 'Skynner', 'Cecely', 'Male', '38 Grasskamp Court', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00128', 'Glenda', 'Inkin', 'Fewster', 'Genderfluid', '1 Del Mar Parkway', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00129', 'Hogan', 'Ciobotaro', 'Petts', 'Agender', '66 Elgar Lane', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00130', 'Reinald', 'Gravenor', 'Batha', 'Polygender', '6 8th Parkway', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00131', 'Ulrick', 'Scholey', 'Hamp', 'Female', '779 Mariners Cove Point', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00132', 'Bentlee', 'Scain', 'Baptist', 'Genderqueer', '95 Anhalt Hill', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00133', 'Pammi', 'McRonald', 'Vedenyakin', 'Genderqueer', '92 Forster Alley', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00134', 'Amby', 'Defries', 'Como', 'Male', '13152 Corscot Hill', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00135', 'Jaquelyn', 'Victoria', 'Alcalde', 'Male', '89 Carey Place', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00136', 'Ira', 'Duplan', 'Spaducci', 'Male', '355 Pond Way', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00137', 'Orel', 'Logsdale', 'Harbinson', 'Bigender', '044 Prairieview Center', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00138', 'Deanne', 'Charlewood', 'Sherrett', 'Male', '14 Packers Road', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00139', 'Hansiain', 'Kynder', 'Loughhead', 'Bigender', '27 Rutledge Lane', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00140', 'Gino', 'Petruk', 'Andrin', 'Agender', '362 Twin Pines Road', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00141', 'Dania', 'Roe', 'Perton', 'Genderfluid', '11333 Corben Terrace', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00142', 'Michale', 'Guiett', 'Longthorn', 'Non-binary', '6 Lakeland Alley', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00143', 'Tish', 'Bontoft', 'Burthom', 'Non-binary', '5 Butterfield Trail', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00144', 'Helli', 'Tukesby', 'Skirven', 'Bigender', '20 Tony Road', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00145', 'Marsha', 'Graysmark', 'Holhouse', 'Polygender', '06 Derek Park', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00146', 'Enrika', 'Delamar', 'Skones', 'Male', '154 Commercial Junction', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00147', 'Ashlin', 'Carle', 'Ludron', 'Genderfluid', '0808 Fieldstone Way', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00148', 'Ware', 'Martinyuk', 'Jurgensen', 'Non-binary', '5953 Arizona Pass', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00149', 'Lynna', 'Robathon', 'Grogor', 'Bigender', '46290 Heath Street', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00150', 'Pernell', 'Benjafield', 'Gisbye', 'Genderfluid', '45977 Goodland Road', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00151', 'Marilee', 'Mathewes', 'Surgey', 'Agender', '2585 Grover Place', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00152', 'Jan', 'Petera', 'Gheorghie', 'Non-binary', '5336 Little Fleur Alley', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00153', 'Kent', 'Casbolt', 'Howley', 'Genderfluid', '0 Nevada Center', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00154', 'Bryan', 'Diemer', 'Treffry', 'Agender', '3699 Golf View Terrace', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00155', 'Gavrielle', 'Papaminas', 'Casserley', 'Female', '0762 Katie Center', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00156', 'Kipper', 'Woollard', 'Prescot', 'Polygender', '911 Talmadge Point', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00157', 'Miriam', 'Yosselevitch', 'Whetson', 'Genderqueer', '01898 Chinook Junction', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00158', 'Mallory', 'Carslake', 'Stears', 'Non-binary', '557 Cherokee Junction', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00159', 'Randene', 'Surfleet', 'Greenlees', 'Agender', '54346 Gulseth Point', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00160', 'Judie', 'Heliet', 'Winterflood', 'Genderqueer', '4 Crowley Hill', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00161', 'Else', 'Abbate', 'Ainger', 'Female', '296 Katie Pass', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00162', 'Tiebout', 'Waddup', 'Wiley', 'Genderqueer', '2 Lukken Center', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00163', 'Cleopatra', 'Gerring', 'Whitehorn', 'Agender', '48 Chive Junction', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00164', 'Henrik', 'Shepeard', 'Blagbrough', 'Agender', '3669 Sauthoff Park', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00165', 'Giustino', 'McCall', 'Gilardone', 'Polygender', '9 Drewry Drive', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00166', 'Ky', 'Kenneway', 'Woodard', 'Female', '4 Kings Hill', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00167', 'Charley', 'Kinsley', 'Mussett', 'Agender', '60 Sullivan Trail', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00168', 'Fin', 'Pauncefoot', 'Trebilcock', 'Non-binary', '302 Mifflin Alley', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00169', 'Ninon', 'Stirman', 'Pringley', 'Non-binary', '2 Wayridge Road', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00170', 'Town', 'Kinningley', 'Ainsley', 'Male', '60 Thackeray Drive', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00171', 'Dunc', 'Emerson', 'Locard', 'Bigender', '06889 Calypso Street', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00172', 'Hasty', 'Heel', 'Still', 'Genderfluid', '4755 Carpenter Point', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00173', 'Zed', 'Doche', 'Collister', 'Non-binary', '80760 Old Shore Park', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00174', 'Barr', 'Cescotti', 'Derrett', 'Polygender', '0 Autumn Leaf Court', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00175', 'Claudine', 'Taylorson', 'Comolli', 'Non-binary', '34 Basil Plaza', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00176', 'Emeline', 'Brownsill', 'Abbet', 'Genderqueer', '097 Logan Junction', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00177', 'Alick', 'Woodwin', 'Stemp', 'Polygender', '92868 Dixon Alley', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00178', 'Wendy', 'Anderbrugge', 'Benfield', 'Male', '4226 David Avenue', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00179', 'Kim', 'Siemon', 'Sellen', 'Non-binary', '04381 Dovetail Place', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00180', 'Calvin', 'Lyddon', 'Dahmke', 'Female', '59013 Anniversary Street', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00181', 'Milo', 'Gilardone', 'Crewther', 'Polygender', '677 High Crossing Road', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00182', 'Keelby', 'Matusovsky', 'Gethouse', 'Agender', '5578 Norway Maple Drive', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00183', 'Cosetta', 'Jex', 'Dixcee', 'Genderqueer', '32112 Di Loreto Terrace', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00184', 'Danyette', 'Blonfield', 'Makey', 'Female', '9847 Parkside Junction', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00185', 'Mareah', 'Hudless', 'Spaducci', 'Agender', '52 Marcy Park', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00186', 'Constantino', 'Parkman', 'Blanket', 'Agender', '3981 Vera Alley', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00187', 'Emalee', 'Simeoli', 'Werendell', 'Genderfluid', '8714 Caliangt Pass', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00188', 'Shelbi', 'O''Brallaghan', 'Jaskowicz', 'Polygender', '33677 Gulseth Circle', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00189', 'Cherrita', 'Kordovani', 'Sedwick', 'Bigender', '5 Cottonwood Plaza', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00190', 'Guillema', 'Yarker', 'Mattam', 'Female', '3 Oak Valley Circle', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00191', 'Francyne', 'Rein', 'Maymond', 'Female', '1536 Dexter Circle', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00192', 'Heall', 'Posselow', 'Nicholas', 'Female', '435 Hermina Hill', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00193', 'Nickie', 'Belsher', 'Breit', 'Non-binary', '739 Meadow Valley Lane', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00194', 'Darrin', 'Whatmough', 'Lowrance', 'Non-binary', '09 Duke Junction', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00195', 'Feliks', 'Billings', 'Rathe', 'Genderfluid', '475 Golden Leaf Center', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00196', 'Giuseppe', 'Mounfield', 'Pobjay', 'Non-binary', '00076 Sommers Alley', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00197', 'Mollie', 'Hanmer', 'Dumigan', 'Polygender', '447 Schlimgen Crossing', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00198', 'Antoine', 'Tavernor', 'Crosse', 'Male', '5138 Bayside Point', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00199', 'Maura', 'Calan', 'Magowan', 'Polygender', '89575 Hayes Hill', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00200', 'Car', 'Buer', 'Mityushkin', 'Agender', '603 Cordelia Plaza', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00201', 'Mabel', 'Balaison', 'Windibank', 'Male', '42 Oak Valley Plaza', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00202', 'Carry', 'Wasson', 'Crepin', 'Female', '9887 Farragut Pass', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00203', 'Ulrick', 'Walton', 'Crosthwaite', 'Polygender', '42 Katie Park', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00204', 'Benedetto', 'Simper', 'Probate', 'Non-binary', '469 Hintze Street', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00205', 'Sadie', 'Pinches', 'Arnet', 'Male', '7995 Pleasure Junction', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00206', 'Colette', 'Sands-Allan', 'Flisher', 'Polygender', '9626 Westridge Way', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00207', 'Rozamond', 'Keddey', 'Feaster', 'Male', '8 Crest Line Center', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00208', 'Codi', 'Trebble', 'Kynton', 'Non-binary', '8 Red Cloud Road', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00209', 'Vidovic', 'Thamelt', 'Teas', 'Non-binary', '80 Bonner Street', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00210', 'Mason', 'Stelljes', 'Suddaby', 'Genderfluid', '5506 Anhalt Court', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00211', 'Kimbra', 'Fedoronko', 'Courtois', 'Non-binary', '5986 Ruskin Terrace', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00212', 'Cletis', 'Oxteby', 'Swine', 'Genderqueer', '56 Hooker Pass', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00213', 'Shelli', 'Burghill', 'Farnill', 'Polygender', '2 Ruskin Way', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00214', 'Arleyne', 'Staresmeare', 'Rousell', 'Polygender', '05353 Forster Pass', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00215', 'Ethyl', 'Vesco', 'Beevers', 'Agender', '0 Schurz Drive', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00216', 'Fern', 'Chadbourn', 'Gutowska', 'Genderqueer', '2 Mallory Alley', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00217', 'Julio', 'O''Ruane', 'Jarry', 'Agender', '79 Mosinee Alley', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00218', 'Zarla', 'Bosdet', 'Giffard', 'Agender', '9 Larry Park', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00219', 'Rip', 'Collingwood', 'Plastow', 'Non-binary', '8 Summit Place', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00220', 'Billy', 'Jeves', 'Perris', 'Polygender', '3 Ludington Hill', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00221', 'Lizzy', 'Backsal', 'Jowers', 'Male', '6970 Porter Drive', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00222', 'Corry', 'Knill', 'Creer', 'Genderfluid', '644 Gina Hill', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00223', 'Yvonne', 'Blackmoor', 'Warmisham', 'Female', '50945 Mendota Crossing', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00224', 'Zechariah', 'Domesday', 'Rickell', 'Male', '47831 Little Fleur Drive', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00225', 'Shari', 'Tatham', 'Faas', 'Polygender', '239 Porter Alley', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00226', 'Niel', 'Feltham', 'Aronson', 'Non-binary', '7076 Parkside Lane', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00227', 'Sarita', 'Ivankin', 'Kiebes', 'Female', '7533 Dakota Parkway', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00228', 'Leupold', 'Fould', 'de Wilde', 'Bigender', '88 Vernon Trail', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00229', 'Reggy', 'Herrero', 'Van den Dael', 'Agender', '270 Miller Drive', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00230', 'Tabbie', 'Gladbeck', 'Montacute', 'Male', '7 Oneill Drive', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00231', 'Susi', 'McGarrity', 'Pudney', 'Non-binary', '117 Mendota Plaza', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00232', 'Bobbie', 'Tooze', 'Couthard', 'Female', '0044 Fremont Terrace', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00233', 'Silvio', 'Goodyear', 'Shippey', 'Non-binary', '0 Menomonie Trail', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00234', 'Ula', 'Heild', 'Cluelow', 'Genderqueer', '96 Havey Terrace', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00235', 'Tyrone', 'Nelissen', 'Balassi', 'Genderqueer', '76 Knutson Center', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00236', 'Oona', 'Blakemore', 'Chatainier', 'Female', '8949 Dwight Circle', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00237', 'Jackqueline', 'Muffett', 'Rathbourne', 'Polygender', '296 Service Park', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00238', 'Vern', 'Lindop', 'Prin', 'Agender', '07 Crest Line Lane', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00239', 'Eldin', 'Hearthfield', 'Loreit', 'Agender', '2 Acker Junction', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00240', 'Osbourn', 'Twell', 'Benford', 'Agender', '4 Arrowood Lane', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00241', 'Ivar', 'Lade', 'Matzel', 'Polygender', '14874 Mosinee Plaza', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00242', 'Elissa', 'Meneur', 'Skiggs', 'Bigender', '66100 Mariners Cove Street', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00243', 'Cly', 'Macieiczyk', 'Tritten', 'Bigender', '282 South Terrace', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00244', 'Bonita', 'Gilling', 'Sinclar', 'Polygender', '3545 Algoma Way', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00245', 'Kassey', 'Fishpond', 'Loughlan', 'Genderfluid', '556 Kingsford Point', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00246', 'Estella', 'Jillett', 'Jirasek', 'Polygender', '94471 Boyd Road', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00247', 'Allin', 'Muck', 'Keyzman', 'Genderqueer', '3 Maple Place', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00248', 'Nikaniki', 'Allmark', 'Evreux', 'Female', '351 Lindbergh Park', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00249', 'Shae', 'Audley', 'Rojas', 'Non-binary', '952 Dayton Crossing', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00250', 'Thorn', 'Rainbird', 'Inger', 'Genderqueer', '49 Memorial Place', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00251', 'Orazio', 'Kruger', 'Dmytryk', 'Bigender', '73 Sullivan Lane', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00252', 'Gorden', 'Dionis', 'Matyushkin', 'Genderqueer', '0752 Del Sol Hill', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00253', 'Yorgos', 'Doreward', 'Edmett', 'Genderqueer', '1 Susan Drive', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00254', 'Regan', 'Bartczak', 'Temple', 'Female', '7756 Homewood Lane', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00255', 'Reggi', 'Jacks', 'Crasford', 'Non-binary', '9 Sutherland Crossing', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00256', 'Colet', 'O''Dare', 'Stringer', 'Genderqueer', '0 Bultman Terrace', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00257', 'Mariam', 'Gibbons', 'Bilyard', 'Genderfluid', '1 Autumn Leaf Place', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00258', 'Nevins', 'Howley', 'Mateu', 'Polygender', '1 Golden Leaf Street', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00259', 'Shelley', 'Ungerechts', 'Dumsday', 'Agender', '5 Delladonna Center', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00260', 'Mozes', 'Adenot', 'Poyner', 'Genderfluid', '1 Gina Alley', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00261', 'Brandais', 'Jewise', 'Durant', 'Genderqueer', '22059 Jackson Alley', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00262', 'Claudelle', 'Sainz', 'Shawel', 'Female', '205 Melody Hill', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00263', 'Lorens', 'Nazareth', 'Swetland', 'Genderqueer', '4141 Elka Avenue', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00264', 'Ardith', 'Robertazzi', 'Doughill', 'Genderqueer', '7 Oneill Park', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00265', 'Horacio', 'Thandi', 'Callear', 'Non-binary', '79555 Stephen Junction', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00266', 'Gino', 'Lernihan', 'Leason', 'Agender', '5 Iowa Avenue', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00267', 'Erinn', 'Slee', 'Donnersberg', 'Genderqueer', '1 Paget Junction', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00268', 'Nerti', 'Wombwell', 'Cannavan', 'Polygender', '6422 Mccormick Way', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00269', 'Paton', 'Chadd', 'Walcar', 'Non-binary', '73557 West Parkway', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00270', 'Margeaux', 'Garvie', 'Wibrow', 'Agender', '0 Tennyson Center', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00271', 'Jose', 'Floris', 'Sandyfirth', 'Non-binary', '65544 Clemons Place', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00272', 'Sandy', 'Websdale', 'Costan', 'Non-binary', '0124 Bashford Hill', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00273', 'Lind', 'Leven', 'Doorbar', 'Polygender', '8386 Surrey Parkway', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00274', 'Christabel', 'Bullivent', 'Tumpane', 'Female', '1 Ryan Street', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00275', 'Emmaline', 'Jaeggi', 'Quartley', 'Non-binary', '91906 Holy Cross Circle', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00276', 'Yorker', 'Osgar', 'Sowter', 'Non-binary', '041 Arizona Crossing', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00277', 'Fay', 'Holdey', 'Artrick', 'Genderqueer', '6003 Roth Road', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00278', 'Joycelin', 'Maylin', 'Spurway', 'Male', '125 Tennyson Center', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00279', 'Janice', 'Dockreay', 'Yearns', 'Male', '11 Clarendon Alley', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00280', 'Gwenni', 'Dressel', 'MacAindreis', 'Polygender', '8772 Monica Drive', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00281', 'Hedi', 'Trotman', 'Rorke', 'Male', '086 Thackeray Parkway', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00282', 'Coreen', 'Duchesne', 'Cabera', 'Bigender', '662 Kim Court', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00283', 'Ebonee', 'Kembley', 'Reaman', 'Female', '6331 Ilene Hill', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00284', 'Godfree', 'Harmant', 'Vescovini', 'Agender', '89 Merrick Plaza', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00285', 'Stu', 'Tobias', 'Sproul', 'Polygender', '388 Badeau Parkway', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00286', 'Blakeley', 'Atlay', 'Nawton', 'Non-binary', '7077 Clove Avenue', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00287', 'Brendon', 'Semiras', 'Braven', 'Genderfluid', '92 Goodland Circle', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00288', 'Hadley', 'Kalkofen', 'O''Sheils', 'Agender', '83807 Thierer Street', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00289', 'Lindsey', 'Lindell', 'Robbey', 'Genderfluid', '317 Erie Parkway', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00290', 'Sayer', 'Enrico', 'Barkess', 'Agender', '54263 Union Center', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00291', 'Taffy', 'Fenck', 'Allawy', 'Female', '7 Del Sol Terrace', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00292', 'Abrahan', 'Charrier', 'Jordon', 'Agender', '1943 Sutteridge Plaza', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00293', 'Margalo', 'Macklam', 'Crabtree', 'Polygender', '0454 Buell Parkway', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00294', 'Carilyn', 'Somerville', 'Priestner', 'Polygender', '007 Harbort Hill', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00295', 'Yuri', 'Harmour', 'Giuron', 'Male', '3 Grim Place', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00296', 'Matilda', 'McKintosh', 'Toop', 'Male', '6 Knutson Junction', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00297', 'Mellisent', 'Tilmouth', 'MacCroary', 'Male', '8567 Autumn Leaf Drive', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00298', 'Betti', 'Whinney', 'Hockell', 'Female', '236 Sage Crossing', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00299', 'Isak', 'Larenson', 'Weetch', 'Bigender', '9488 Rowland Way', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00300', 'Jack', 'Spellicy', 'Greatland', 'Male', '45842 Twin Pines Lane', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00301', 'Matti', 'Dunstall', 'Kryzhov', 'Polygender', '717 Sunfield Lane', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00302', 'Madge', 'Gairdner', 'Niessen', 'Agender', '93271 Di Loreto Street', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00303', 'Drucy', 'Hardern', 'Coultar', 'Polygender', '2875 Northwestern Road', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00304', 'Ermanno', 'Martusov', 'Crimpe', 'Agender', '34857 Ohio Lane', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00305', 'Daisy', 'Pattullo', 'Arblaster', 'Male', '809 Oak Valley Alley', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00306', 'Bartlet', 'Anthona', 'MacAllaster', 'Bigender', '6230 Basil Court', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00307', 'Jozef', 'Mixworthy', 'McQuilty', 'Female', '53 Merry Avenue', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00308', 'Dalis', 'Feuell', 'Michel', 'Male', '4376 Moose Point', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00309', 'Benjy', 'MacConnulty', 'Chomicz', 'Genderfluid', '79 Homewood Pass', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00310', 'Sharyl', 'Starking', 'Biasotti', 'Non-binary', '42449 Golf View Crossing', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00311', 'Vincents', 'Kira', 'McGinney', 'Non-binary', '12 Mariners Cove Alley', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00312', 'Marleah', 'Ellershaw', 'Pechan', 'Bigender', '59 Spohn Hill', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00313', 'Stevy', 'Ebben', 'Dury', 'Bigender', '50 Hintze Park', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00314', 'Arron', 'Balharrie', 'Patterfield', 'Bigender', '4 Aberg Crossing', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00315', 'Marita', 'Furmenger', 'Van Der Walt', 'Agender', '23556 Basil Junction', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00316', 'Alyda', 'Spurling', 'Cavaney', 'Male', '0389 Reindahl Terrace', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00317', 'Xena', 'Ebbitt', 'Fullard', 'Male', '61966 Warrior Court', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00318', 'Gertrude', 'Dana', 'Adamoli', 'Polygender', '9110 Bay Parkway', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00319', 'Tailor', 'Belvard', 'Glassopp', 'Female', '4 Birchwood Trail', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00320', 'Nolie', 'Comiam', 'Wildsmith', 'Female', '8 Reinke Road', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00321', 'Viola', 'Lantry', 'Maudsley', 'Bigender', '70813 Dixon Trail', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00322', 'Iver', 'Mityakov', 'Rodder', 'Agender', '8180 Memorial Pass', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00323', 'Farrel', 'Branchett', 'Buesnel', 'Agender', '8 Sheridan Center', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00324', 'Alley', 'Carlone', 'Huxster', 'Bigender', '9 Doe Crossing Lane', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00325', 'Meredithe', 'Zink', 'Blampey', 'Polygender', '32216 School Avenue', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00326', 'Laina', 'Danett', 'Partlett', 'Female', '0 Carey Center', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00327', 'Alverta', 'Saunder', 'Deevey', 'Agender', '676 Esker Junction', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00328', 'Dixie', 'Nelles', 'Mackerness', 'Polygender', '9 Elka Avenue', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00329', 'Tory', 'Churm', 'Grove', 'Male', '0864 Pearson Park', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00330', 'Osborne', 'Lathleiff', 'Kennifeck', 'Polygender', '51 Corscot Alley', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00331', 'Sollie', 'BURWIN', 'Helliker', 'Bigender', '73051 Burning Wood Terrace', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00332', 'Geoffry', 'Peasgood', 'Bisacre', 'Genderqueer', '79691 Katie Center', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00333', 'Tracy', 'Blaw', 'Johansson', 'Female', '4 Stone Corner Point', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00334', 'Belle', 'Laphorn', 'Madrell', 'Male', '090 Lake View Center', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00335', 'Erskine', 'Trevino', 'Hayward', 'Non-binary', '3 Lakewood Hill', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00336', 'Ricki', 'Penhaligon', 'Kinforth', 'Genderqueer', '25576 Stephen Center', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00337', 'Roarke', 'Qusklay', 'Petti', 'Genderqueer', '207 Browning Center', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00338', 'Delphine', 'Lorek', 'Claiton', 'Agender', '6 Redwing Place', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00339', 'Everett', 'Tolmie', 'Tokell', 'Genderfluid', '8 Heath Hill', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00340', 'Rodolphe', 'Wogdon', 'Cejka', 'Genderqueer', '79 Thackeray Crossing', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00341', 'Scarface', 'Bradfield', 'Drysdale', 'Polygender', '020 Derek Circle', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00342', 'Jecho', 'Fernier', 'Gallafant', 'Female', '943 Bluejay Lane', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00343', 'Bessie', 'Crosfield', 'Rymill', 'Male', '3423 Iowa Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00344', 'Hersh', 'MacAirt', 'Bulter', 'Female', '500 Homewood Park', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00345', 'Georgina', 'Collidge', 'Toogood', 'Genderqueer', '2 Rieder Drive', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00346', 'Gualterio', 'Bernolet', 'Feander', 'Genderqueer', '460 Crowley Center', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00347', 'Teodoor', 'Easum', 'Samwyse', 'Bigender', '55 Kropf Avenue', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00348', 'Darbee', 'Danter', 'Glynn', 'Bigender', '2712 Lakewood Trail', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00349', 'Homere', 'Gasking', 'Leadston', 'Genderqueer', '66127 Corscot Court', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00350', 'Hastings', 'Millbank', 'Tatham', 'Polygender', '9719 Norway Maple Center', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00351', 'Humfrey', 'Babin', 'Godney', 'Polygender', '9167 Fieldstone Terrace', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00352', 'Moore', 'Mayer', 'Favey', 'Polygender', '461 Doe Crossing Circle', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00353', 'Lenora', 'Waight', 'Burgh', 'Agender', '80671 Debra Pass', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00354', 'Harriette', 'Shorthill', 'Barrass', 'Bigender', '433 Homewood Road', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00355', 'Lyell', 'Comelli', 'Kyngdon', 'Bigender', '3 Crescent Oaks Pass', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00356', 'Nap', 'Pyrke', 'Tumielli', 'Polygender', '6138 Maple Wood Avenue', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00357', 'Blaire', 'Vlach', 'Benne', 'Genderfluid', '77946 Dorton Avenue', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00358', 'Storm', 'Charlwood', 'Pridgeon', 'Genderfluid', '0762 Garrison Circle', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00359', 'Robbie', 'Snoding', 'Bingham', 'Non-binary', '68 Mcbride Trail', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00360', 'Eugine', 'Mapowder', 'Propper', 'Polygender', '87 Briar Crest Avenue', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00361', 'Whitman', 'Ridesdale', 'Pryce', 'Male', '1 Coolidge Hill', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00362', 'Dode', 'Neely', 'Worster', 'Bigender', '62 Meadow Ridge Road', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00363', 'Cammy', 'Brydson', 'Tripe', 'Polygender', '50 Schurz Drive', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00364', 'Lira', 'Crutchfield', 'Jeves', 'Genderqueer', '161 Service Trail', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00365', 'Daffie', 'Nisot', 'Cooke', 'Female', '027 Scott Center', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00366', 'Bartlet', 'Northern', 'Dillway', 'Bigender', '756 Briar Crest Point', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00367', 'Reggy', 'Boness', 'Lernihan', 'Male', '0634 Stoughton Place', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00368', 'Gabi', 'Bengtsson', 'Julien', 'Non-binary', '96 Annamark Place', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00369', 'Ambrosio', 'Simpkiss', 'Domb', 'Bigender', '921 Eggendart Alley', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00370', 'Worthy', 'McKeon', 'Canny', 'Genderfluid', '11236 Boyd Street', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00371', 'Regen', 'Tomalin', 'Roughsedge', 'Polygender', '6 Roxbury Place', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00372', 'Terrence', 'Gravener', 'Ferruzzi', 'Bigender', '984 Buena Vista Road', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00373', 'Coreen', 'Routh', 'Boffin', 'Agender', '48 Elmside Road', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00374', 'Caitrin', 'Stenyng', 'Alflatt', 'Genderqueer', '4 Thierer Lane', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00375', 'Sander', 'Stert', 'Orteaux', 'Bigender', '0 Packers Street', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00376', 'Caron', 'Maffeo', 'Cassidy', 'Non-binary', '348 Sutteridge Place', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00377', 'Kipp', 'Teasell', 'Delahunty', 'Genderfluid', '597 American Ash Drive', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00378', 'Jdavie', 'Tuther', 'Mc Curlye', 'Agender', '7391 Judy Park', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00379', 'Rubi', 'Walthew', 'Varker', 'Genderqueer', '98733 Norway Maple Crossing', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00380', 'Crawford', 'Garroway', 'Gudgion', 'Genderqueer', '6268 Fisk Junction', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00381', 'Lilas', 'Redsull', 'Gariff', 'Genderfluid', '54888 Atwood Point', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00382', 'Fairleigh', 'Bastian', 'Stimpson', 'Polygender', '4544 Bluejay Avenue', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00383', 'Laney', 'Mettetal', 'Tolmie', 'Bigender', '490 Caliangt Terrace', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00384', 'Nikita', 'Imlacke', 'Cord', 'Non-binary', '1515 Amoth Center', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00385', 'Clio', 'Taig', 'Paszak', 'Bigender', '363 Mccormick Way', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00386', 'Angelico', 'Dunbobin', 'Antunez', 'Polygender', '506 Bunting Trail', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00387', 'Simonette', 'Sarginson', 'Dillaway', 'Agender', '70583 Sundown Center', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00388', 'Terri', 'Aysh', 'Wordley', 'Genderqueer', '87573 Fairfield Plaza', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00389', 'Shanan', 'Walter', 'Ranyell', 'Genderfluid', '4 Scofield Hill', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00390', 'Ange', 'Donahue', 'Halwell', 'Female', '2779 Doe Crossing Crossing', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00391', 'Pascal', 'Causier', 'Carpenter', 'Agender', '6062 American Ash Parkway', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00392', 'Maxwell', 'Vallance', 'Schwander', 'Non-binary', '72 Columbus Alley', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00393', 'Lay', 'Wibberley', 'Smith', 'Agender', '0 Sycamore Park', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00394', 'Zak', 'Cappel', 'Beilby', 'Non-binary', '083 Hovde Plaza', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00395', 'Roda', 'Gatchell', 'Kuzemka', 'Non-binary', '1904 Monument Junction', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00396', 'Clareta', 'McLafferty', 'Dufer', 'Genderqueer', '82346 Eagan Parkway', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00397', 'Luis', 'Parks', 'Stoke', 'Agender', '4735 Menomonie Avenue', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00398', 'Olenolin', 'MacGuffie', 'Hostan', 'Non-binary', '0 Ridgeway Plaza', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00399', 'Rosalyn', 'Walshe', 'Langland', 'Genderfluid', '245 Hintze Court', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00400', 'Caddric', 'Martugin', 'Castanie', 'Non-binary', '8 Comanche Avenue', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00401', 'Xymenes', 'Fould', 'Worlidge', 'Agender', '0 Heath Hill', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00402', 'Lorraine', 'Schirok', 'Tofanelli', 'Male', '0 Green Ridge Pass', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00403', 'Evanne', 'Pozzo', 'Pilch', 'Genderfluid', '05 Magdeline Plaza', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00404', 'Rorie', 'Clashe', 'Knevit', 'Female', '6542 Northview Circle', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00405', 'Nathanil', 'Schlagh', 'Winslett', 'Genderfluid', '6970 Del Mar Street', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00406', 'Jill', 'Leacock', 'Beecraft', 'Polygender', '48563 Starling Court', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00407', 'Ellie', 'Curman', 'Blague', 'Genderfluid', '633 Bluejay Terrace', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00408', 'Sherlock', 'Cahen', 'Klesl', 'Polygender', '908 Straubel Court', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00409', 'Valencia', 'Miranda', 'Clapham', 'Female', '4 Ruskin Parkway', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00410', 'Etan', 'Terbrug', 'Labrone', 'Female', '649 Pond Trail', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00411', 'Bartolomeo', 'Andress', 'Jankovsky', 'Polygender', '148 Laurel Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00412', 'Dorrie', 'Tewkesberry', 'Erickssen', 'Non-binary', '99 Katie Trail', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00413', 'Kayla', 'Mearns', 'Hussey', 'Genderqueer', '2 Ridge Oak Terrace', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00414', 'Barbie', 'Spenton', 'Benmore', 'Non-binary', '4 Service Center', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00415', 'Daile', 'Aronov', 'Burtt', 'Polygender', '61 Dahle Avenue', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00416', 'Kippy', 'Drinkhall', 'Dobrovolny', 'Genderfluid', '558 Cascade Parkway', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00417', 'Northrop', 'Amiss', 'Hanburry', 'Male', '54516 Maryland Junction', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00418', 'Ester', 'Scotson', 'Risdale', 'Genderqueer', '168 Waywood Hill', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00419', 'Elisha', 'Lyddon', 'O'' Mullan', 'Genderfluid', '233 Almo Terrace', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00420', 'Martina', 'Paireman', 'Harrap', 'Agender', '7 Park Meadow Terrace', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00421', 'Sigrid', 'Barbey', 'Barnish', 'Non-binary', '1 Pearson Junction', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00422', 'Millicent', 'Delaprelle', 'Howe', 'Polygender', '318 Lighthouse Bay Road', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00423', 'Aksel', 'Paschke', 'Kingsmill', 'Male', '210 3rd Terrace', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00424', 'Elwood', 'Mayger', 'Elfes', 'Non-binary', '365 Moland Trail', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00425', 'Win', 'Bower', 'Crispin', 'Female', '37 Manitowish Pass', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00426', 'Caresse', 'Hannaway', 'Hickinbottom', 'Agender', '1997 Surrey Alley', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00427', 'Lilla', 'McPake', 'Brislen', 'Female', '68 Birchwood Crossing', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00428', 'Farand', 'Haug', 'Barz', 'Female', '89 Anderson Road', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00429', 'Arlen', 'Woodus', 'Renton', 'Female', '86 Harbort Drive', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00430', 'Rolph', 'Orleton', 'Duggleby', 'Genderqueer', '94 Northfield Alley', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00431', 'Amerigo', 'Ault', 'Willden', 'Polygender', '3 Butterfield Place', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00432', 'Silvan', 'McClory', 'Lenham', 'Agender', '7236 Sullivan Court', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00433', 'Lenna', 'Este', 'Utteridge', 'Non-binary', '88 Columbus Road', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00434', 'Miles', 'Grindell', 'Mecozzi', 'Agender', '6355 Portage Crossing', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00435', 'Trenna', 'Giannotti', 'Ruppele', 'Female', '985 Springs Drive', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00436', 'Kippie', 'Aleveque', 'Gorioli', 'Genderfluid', '998 Myrtle Street', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00437', 'Gusella', 'Bennen', 'Wallentin', 'Bigender', '76832 Namekagon Hill', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00438', 'Micki', 'Bleby', 'Josephs', 'Non-binary', '53 Lien Park', 11, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00439', 'Cristabel', 'Gellett', 'Sutherington', 'Polygender', '6 Clarendon Parkway', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00440', 'Jobyna', 'Cardall', 'Westhofer', 'Non-binary', '5653 Stoughton Circle', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00441', 'Dev', 'Candish', 'O''Corrane', 'Genderqueer', '72525 Pearson Point', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00442', 'Brunhilde', 'McLemon', 'Slaten', 'Bigender', '2 Granby Junction', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00443', 'Giselbert', 'Start', 'Tomaskunas', 'Genderfluid', '40571 Sauthoff Pass', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00444', 'Ewell', 'Elgey', 'Reisenberg', 'Genderqueer', '4 Namekagon Plaza', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00445', 'Gibbie', 'McCrudden', 'Checklin', 'Male', '20 Del Mar Trail', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00446', 'Davy', 'Smidmore', 'Feakins', 'Genderfluid', '38978 Rutledge Center', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00447', 'Adan', 'Murthwaite', 'Lappin', 'Genderqueer', '5 Erie Way', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00448', 'Red', 'Gockelen', 'Maffini', 'Genderqueer', '3271 Northwestern Road', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00449', 'Tades', 'Cottu', 'Neesham', 'Agender', '8 Katie Way', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00450', 'Aylmer', 'Gaskal', 'Flintiff', 'Non-binary', '816 Bobwhite Terrace', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00451', 'Junie', 'Crunkhurn', 'Raymen', 'Genderfluid', '25446 Chive Hill', 14, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00452', 'Jaymee', 'Silverthorne', 'Norsworthy', 'Polygender', '14 Fieldstone Place', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00453', 'Coretta', 'Radbond', 'Nuemann', 'Genderqueer', '1357 1st Pass', 14, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00454', 'Dave', 'Frend', 'Taffley', 'Genderqueer', '067 Dennis Trail', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00455', 'Cherie', 'Cureton', 'Gillmor', 'Male', '8 Lukken Drive', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00456', 'Zia', 'Muscroft', 'Cranney', 'Agender', '5 8th Street', 12, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00457', 'Hildegaard', 'Tinto', 'Lownsbrough', 'Male', '773 Dayton Crossing', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00458', 'Saidee', 'Puddin', 'Lundon', 'Genderqueer', '5 Chinook Avenue', 16, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00459', 'Drona', 'Lusgdin', 'Hartegan', 'Bigender', '99 Valley Edge Park', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00460', 'Worth', 'Fernanando', 'Poynser', 'Polygender', '9 Homewood Hill', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00461', 'Carmine', 'Gobolos', 'Sedger', 'Male', '537 Gina Alley', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00462', 'Val', 'Befroy', 'Rowaszkiewicz', 'Male', '54 Buell Hill', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00463', 'Hally', 'Sperrett', 'Bulward', 'Genderqueer', '6 Donald Circle', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00464', 'Marketa', 'Gleadle', 'Rowswell', 'Bigender', '335 American Ash Plaza', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00465', 'Nealson', 'Mault', 'Terrazzo', 'Male', '4 Beilfuss Crossing', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00466', 'Lyman', 'Mation', 'Order', 'Bigender', '310 School Park', 14, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00467', 'Clemente', 'Morffew', 'Hinge', 'Polygender', '5 David Avenue', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00468', 'Reena', 'Dobbson', 'Meekin', 'Bigender', '95 Russell Lane', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00469', 'Alyssa', 'Jeal', 'Colam', 'Female', '2061 Loomis Center', 12, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00470', 'Toddie', 'Grisdale', 'Covet', 'Agender', '231 Tony Trail', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00471', 'Barnett', 'Paireman', 'Serjeantson', 'Agender', '664 Susan Court', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00472', 'Gav', 'Kloska', 'Summergill', 'Agender', '311 Stoughton Place', 13, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00473', 'Elenore', 'Eaglesham', 'Lorait', 'Genderfluid', '4373 Eastlawn Circle', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00474', 'Linzy', 'Hamsher', 'Eustace', 'Bigender', '68 Columbus Point', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00475', 'Kerianne', 'Durrand', 'Crittal', 'Genderqueer', '03553 Redwing Junction', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00476', 'Edlin', 'Ades', 'Porkiss', 'Female', '73 Schiller Street', 13, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00477', 'Ruthe', 'Ianni', 'Blest', 'Genderqueer', '6 Kings Place', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00478', 'Daryl', 'Dorrell', 'Desaur', 'Polygender', '226 Pawling Park', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00479', 'Jacenta', 'Hartles', 'Hampshaw', 'Genderqueer', '2 Quincy Plaza', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00480', 'Henrietta', 'Treadgall', 'Nevins', 'Bigender', '29547 American Ash Drive', 11, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00481', 'Lukas', 'Faldo', 'Ollenbuttel', 'Male', '3 Kipling Crossing', 15, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00482', 'Gael', 'LAbbet', 'Palphramand', 'Male', '31 Pepper Wood Drive', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00483', 'Lorenzo', 'Spedding', 'Callan', 'Male', '3073 Macpherson Plaza', 15, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00484', 'Gussy', 'Kirtley', 'Rolinson', 'Male', '4060 Derek Pass', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00485', 'Celle', 'Ratke', 'Killelea', 'Genderqueer', '03328 Fulton Drive', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00486', 'Mufinella', 'Daunay', 'Membry', 'Genderqueer', '09721 Bowman Plaza', 11, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00487', 'Caresse', 'Yesenin', 'Pevreal', 'Agender', '86684 Roxbury Plaza', 12, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00488', 'Brinna', 'Huggons', 'Janca', 'Agender', '8955 Arapahoe Point', 16, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00489', 'Raynell', 'Beccero', 'Tolchar', 'Polygender', '219 Del Mar Lane', 14, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00490', 'Aeriel', 'Caress', 'Tarn', 'Male', '516 Graedel Trail', 15, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00491', 'Travers', 'Hammerberg', 'Mundy', 'Male', '43 Arkansas Point', 11, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00492', 'Prisca', 'Lombardo', 'Reck', 'Agender', '44 Del Sol Alley', 16, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00493', 'Welbie', 'O'' Brian', 'Paraman', 'Agender', '1 Londonderry Place', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00494', 'Portie', 'Learmond', 'Grolmann', 'Polygender', '922 Tony Drive', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00495', 'Melonie', 'Hext', 'Dowbiggin', 'Polygender', '1 Dawn Terrace', 16, 9);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00496', 'Abra', 'Brimmell', 'Bouzek', 'Polygender', '7 Mayer Terrace', 15, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00497', 'Barbie', 'Spoerl', 'Awcoate', 'Polygender', '6930 Glendale Junction', 13, 10);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00498', 'Daria', 'McHugh', 'Coldham', 'Bigender', '13057 Pleasure Park', 12, 8);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00499', 'Esme', 'Coppledike', 'Checchi', 'Genderfluid', '74279 Logan Plaza', 13, 7);
insert into students (student_id, first_name, middle_initial, last_name, gender, address, age, grade) values ('S00500', 'Kelley', 'Wickett', 'Praill', 'Genderqueer', '57065 Northwestern Circle', 14, 10);
