insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00001', 'Bendick', 'Pencot', 'Danielian', 11, '566 Crescent Oaks Crossing', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00002', 'Kalvin', 'Wormstone', 'Haestier', 11, '6370 North Avenue', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00003', 'Nariko', 'Winwood', 'Matfield', 12, '805 Dayton Junction', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00004', 'Irina', 'Rembrandt', 'Manhare', 15, '63858 Park Meadow Court', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00005', 'Ynez', 'Yewen', 'Abbett', 15, '86 Susan Street', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00006', 'Rabi', 'Boobier', 'Shorey', 16, '6 South Point', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00007', 'Pall', 'Maddinon', 'Cuxson', 11, '51 2nd Junction', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00008', 'Cosetta', 'Lown', 'Wheowall', 14, '3 Hovde Junction', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00009', 'Regan', 'Nevill', 'Morphey', 16, '96 Del Mar Street', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00010', 'Coletta', 'Holburn', 'Dine-Hart', 15, '8 Ludington Park', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00011', 'April', 'Eves', 'Raoul', 13, '72 Troy Way', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00012', 'Carce', 'Strathern', 'Harfleet', 13, '08015 Milwaukee Lane', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00013', 'Lauraine', 'Brumbie', 'Scurlock', 11, '72763 Little Fleur Hill', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00014', 'Dierdre', 'Lorroway', 'Gilffilland', 16, '99 Rusk Parkway', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00015', 'Magdalene', 'Walrond', 'Steenson', 15, '13418 Elmside Avenue', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00016', 'Erminia', 'Leadbeatter', 'Dunkerley', 15, '34 Sage Trail', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00017', 'Adelind', 'Spivey', 'Nabbs', 15, '8651 Farragut Lane', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00018', 'Maddie', 'O'' Markey', 'Swire', 15, '8 Merchant Junction', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00019', 'Izak', 'Liversley', 'Simanenko', 16, '5 Jay Plaza', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00020', 'Arin', 'McUre', 'Cassley', 15, '379 Fulton Center', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00021', 'Sisile', 'Sheardown', 'Pirri', 12, '3 Little Fleur Way', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00022', 'Kristel', 'Esparza', 'Lober', 14, '0291 Mallard Place', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00023', 'Kary', 'Shooter', 'Aingel', 11, '8015 Dapin Hill', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00024', 'Moise', 'Cluer', 'Dolley', 16, '6 Briar Crest Court', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00025', 'Lelia', 'Horlick', 'Baleine', 11, '99225 Gina Court', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00026', 'Marya', 'Tewkesberry', 'Hendriksen', 16, '0 Cascade Pass', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00027', 'Elisabet', 'Stronough', 'Weldon', 13, '21 Anniversary Trail', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00028', 'Fanechka', 'Kubecka', 'Ryton', 16, '6248 Morrow Avenue', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00029', 'Maye', 'Banfield', 'Thorndale', 12, '3682 Hoffman Court', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00030', 'Avie', 'Duchan', 'Gregoraci', 14, '27 Mayer Drive', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00031', 'Emelda', 'Justice', 'Gooderidge', 12, '862 Mcbride Center', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00032', 'Walther', 'Giacopello', 'Icke', 12, '49 Fordem Drive', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00033', 'Letisha', 'Keeffe', 'Kleingrub', 15, '2737 Drewry Point', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00034', 'Ulises', 'Whopples', 'Duthie', 14, '4 Hanover Lane', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00035', 'Valdemar', 'Phillip', 'Dobsons', 15, '4 Jenifer Parkway', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00036', 'Cele', 'Emps', 'Sainer', 15, '82898 Eagle Crest Hill', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00037', 'Baxie', 'Sacco', 'Eloy', 13, '6213 Center Parkway', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00038', 'Berry', 'Shinton', 'Penquet', 12, '3705 Darwin Alley', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00039', 'Irene', 'Dat', 'M''cowis', 16, '97309 Hallows Park', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00040', 'Catarina', 'Kobpal', 'Elsmere', 11, '33798 Dayton Lane', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00041', 'Obed', 'Cagan', 'Dashkovich', 12, '90354 Derek Road', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00042', 'Guinna', 'Ortler', 'De Ath', 15, '31 2nd Pass', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00043', 'Torie', 'Pidgen', 'Hein', 14, '9992 Hazelcrest Alley', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00044', 'Hasheem', 'Aingell', 'Maasze', 14, '95 Merchant Way', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00045', 'Rube', 'Paolillo', 'Filyaev', 16, '2 Sage Center', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00046', 'Kienan', 'Evetts', 'Winscom', 15, '868 Sutherland Point', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00047', 'Bevin', 'Fuentez', 'Denness', 12, '0 Blackbird Place', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00048', 'Lew', 'M''cowis', 'Raithmill', 13, '498 Butternut Center', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00049', 'Althea', 'Cowlin', 'Maskelyne', 16, '4214 Dottie Avenue', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00050', 'Sherman', 'Simoes', 'Woolley', 11, '6 Pine View Crossing', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00051', 'Elianore', 'Boscott', 'Kneale', 16, '78709 Bowman Pass', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00052', 'Gwendolen', 'Yanson', 'Mattiacci', 16, '07198 Michigan Street', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00053', 'Pat', 'Lockie', 'Threlfall', 16, '502 Sycamore Park', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00054', 'Siffre', 'Sherebrooke', 'Woodworth', 13, '63632 Tomscot Parkway', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00055', 'Blake', 'Voase', 'Shirland', 11, '9 Cottonwood Lane', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00056', 'Guilbert', 'Evers', 'Scolding', 13, '3815 Sachs Avenue', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00057', 'Anna-maria', 'Lazenby', 'Bagley', 11, '6 Warbler Plaza', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00058', 'Sharlene', 'Isaq', 'Stear', 16, '523 Morningstar Circle', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00059', 'Sharron', 'De Rechter', 'Ferguson', 14, '6 Hoard Avenue', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00060', 'Kerrie', 'Crellin', 'Souttar', 14, '20 Continental Park', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00061', 'Hadley', 'Jeanin', 'Rishman', 15, '531 Hayes Hill', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00062', 'Tatum', 'Playfair', 'Rushmer', 11, '9060 Susan Terrace', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00063', 'Linda', 'Stabbins', 'MacCathay', 12, '059 Jenifer Road', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00064', 'Clovis', 'Gerriet', 'Czaple', 15, '6798 Old Shore Center', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00065', 'Iormina', 'Saffin', 'Brilon', 15, '152 Loftsgordon Terrace', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00066', 'Stu', 'Sayburn', 'Mannakee', 12, '779 Truax Way', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00067', 'Royce', 'Banasevich', 'Siddall', 11, '264 Waubesa Place', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00068', 'Chrissie', 'Kermon', 'Kidson', 16, '532 Gerald Point', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00069', 'Dixie', 'St Clair', 'Piburn', 12, '96952 Harper Park', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00070', 'Rodge', 'Easterfield', 'Bonwell', 13, '05 Lukken Hill', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00071', 'Gerda', 'Scade', 'Aimable', 15, '32137 Messerschmidt Parkway', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00072', 'Aldon', 'Clowes', 'Aronstam', 15, '0 Nancy Hill', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00073', 'Lou', 'Sandys', 'Woodhouse', 13, '19031 Macpherson Alley', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00074', 'Kristina', 'Lebrun', 'Lambole', 16, '61097 Holmberg Avenue', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00075', 'Odelinda', 'Zum Felde', 'Yegorkin', 13, '420 Melrose Way', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00076', 'Helge', 'Lenormand', 'Chisholme', 15, '82 Monument Alley', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00077', 'Lammond', 'Shaudfurth', 'Al Hirsi', 14, '425 Utah Drive', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00078', 'Andre', 'Szepe', 'Spalton', 12, '713 Lakewood Gardens Road', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00079', 'Brannon', 'Whenham', 'Liddington', 15, '05038 Sherman Park', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00080', 'Shermy', 'Gearing', 'Farthing', 15, '51 Fulton Pass', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00081', 'Viviana', 'Idale', 'MacQuaker', 15, '6 Northfield Road', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00082', 'Yoko', 'Credland', 'Ovendale', 11, '1 Hoepker Way', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00083', 'Jerome', 'Klaiser', 'Rabl', 12, '067 Washington Circle', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00084', 'Rozanna', 'Meaton', 'Saintpierre', 16, '8980 Westend Alley', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00085', 'Deerdre', 'Lockhart', 'Gelardi', 11, '8 Riverside Road', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00086', 'Kelcie', 'Sinderland', 'Coale', 11, '396 Shasta Terrace', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00087', 'Yoshi', 'Kalinsky', 'Fassmann', 15, '77 Debs Way', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00088', 'Shirley', 'Gniewosz', 'Baldin', 13, '49153 Saint Paul Drive', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00089', 'Sig', 'Gooch', 'Ballaam', 11, '007 Tony Road', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00090', 'Auroora', 'McClure', 'Bachellier', 12, '17596 Dawn Lane', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00091', 'Eryn', 'Stancliffe', 'Strain', 13, '53 Fairview Trail', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00092', 'Dmitri', 'Lynskey', 'Zebedee', 13, '1 Monterey Lane', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00093', 'Merrily', 'Mccaull', 'Beebe', 14, '751 Scott Pass', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00094', 'Willdon', 'Bridie', 'Coales', 14, '6 Blackbird Alley', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00095', 'Pavia', 'Barwell', 'McInteer', 12, '23 Brown Circle', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00096', 'Charmane', 'Mort', 'Stammirs', 11, '916 Mcbride Crossing', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00097', 'Torin', 'Kinnie', 'De Marchi', 13, '6 Ohio Junction', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00098', 'Rozella', 'Bernhardi', 'Shadfourth', 15, '8 Weeping Birch Drive', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00099', 'Andi', 'Arents', 'Pennini', 15, '69 Di Loreto Center', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00100', 'Phoebe', 'Philippe', 'Hazlewood', 14, '5466 Union Crossing', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00101', 'Andy', 'Do', 'Philott', 16, '4 Fair Oaks Junction', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00102', 'Francesco', 'Christaeas', 'Rickeard', 15, '930 Fairview Trail', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00103', 'Esta', 'Machans', 'Lidgely', 12, '3037 Sachs Lane', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00104', 'Dillon', 'Gavey', 'Seemmonds', 16, '1 Merrick Park', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00105', 'Ferdinande', 'Cochran', 'Theobalds', 15, '88 Sherman Point', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00106', 'Faina', 'Overpool', 'MacGowing', 15, '87422 Russell Way', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00107', 'Harmony', 'Blockey', 'Cyples', 14, '77 Charing Cross Crossing', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00108', 'Charisse', 'Hovert', 'Slaney', 16, '719 Onsgard Place', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00109', 'Terrell', 'May', 'Hagerty', 12, '45239 Stuart Circle', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00110', 'Nil', 'Caygill', 'Symms', 13, '18 Bunker Hill Circle', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00111', 'Enid', 'Mattheis', 'McCumskay', 11, '52 Esch Drive', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00112', 'Aveline', 'McPartlin', 'Baud', 11, '2969 Reinke Lane', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00113', 'Yulma', 'Harnell', 'Hawkwood', 15, '22 Arizona Plaza', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00114', 'Stavro', 'Bythell', 'Fenne', 16, '33367 Veith Center', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00115', 'Sapphire', 'Kermott', 'Fearnside', 14, '47 Annamark Way', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00116', 'Odessa', 'Leavold', 'Broxup', 12, '18599 Truax Road', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00117', 'Udall', 'Cuardall', 'Artis', 16, '95961 Summit Court', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00118', 'Tomkin', 'Woodnutt', 'Bordis', 12, '207 Pennsylvania Alley', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00119', 'Agace', 'Entissle', 'Dover', 12, '552 Village Green Crossing', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00120', 'Madlin', 'Agneau', 'Doherty', 15, '34 Norway Maple Road', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00121', 'Genia', 'Sallarie', 'Jamot', 13, '80 Westport Lane', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00122', 'Mariele', 'Eakins', 'Huck', 13, '3 Cordelia Point', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00123', 'Debra', 'Chate', 'Foote', 16, '5 Donald Hill', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00124', 'Carmelita', 'Ridley', 'Upstone', 16, '093 Portage Junction', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00125', 'Delmore', 'Meaton', 'Coopey', 12, '9205 Buhler Parkway', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00126', 'Leena', 'Le Fevre', 'Crockford', 12, '18874 Cordelia Plaza', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00127', 'Noby', 'Walbrook', 'Wilbore', 12, '85 Autumn Leaf Circle', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00128', 'Sharlene', 'Ronchetti', 'Heys', 16, '8 Oxford Park', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00129', 'Sybila', 'Muglestone', 'Klejna', 13, '87377 Colorado Circle', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00130', 'Corri', 'Coleshill', 'Mousley', 12, '8348 Buhler Park', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00131', 'Ellene', 'Marton', 'Ivanovic', 16, '3 4th Court', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00132', 'Toiboid', 'Cornuau', 'Ince', 11, '8 Stoughton Trail', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00133', 'Ashby', 'Glozman', 'Van den Dael', 11, '6524 Hollow Ridge Alley', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00134', 'Valerye', 'Hackworth', 'Hansom', 14, '9517 Kennedy Street', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00135', 'Dawn', 'Yashanov', 'Dubois', 14, '92214 7th Road', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00136', 'Crystal', 'Dyment', 'Rudloff', 16, '0 Memorial Point', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00137', 'Merwin', 'McKechnie', 'Vasilkov', 15, '20 Sundown Circle', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00138', 'Teresa', 'Witten', 'Huriche', 15, '9651 6th Circle', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00139', 'Wilma', 'Guiet', 'Garnul', 16, '55319 Rutledge Road', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00140', 'Harlin', 'Hayward', 'Jeens', 14, '29 Golf Course Junction', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00141', 'Adrianne', 'McLardie', 'Semrad', 16, '6573 Hallows Avenue', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00142', 'Georgie', 'Monery', 'Treffrey', 13, '631 Oak Valley Center', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00143', 'Kermie', 'Hodinton', 'Bauser', 11, '278 Loftsgordon Drive', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00144', 'Cassius', 'Yeowell', 'Eshmade', 14, '088 Lawn Junction', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00145', 'Ethelin', 'Robak', 'Cicutto', 14, '99 Hooker Pass', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00146', 'Hillyer', 'Kevane', 'Filipyev', 16, '14 Bonner Junction', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00147', 'Reginald', 'Arent', 'Sainteau', 15, '97 Namekagon Plaza', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00148', 'Slade', 'Coltart', 'Alenikov', 14, '80 Tony Lane', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00149', 'Garrott', 'Bortoli', 'Hornig', 14, '911 Pankratz Place', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00150', 'Jocelyne', 'Rodda', 'Gerrard', 15, '12278 Mccormick Street', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00151', 'Susan', 'Flaws', 'Blencoe', 15, '874 Elgar Parkway', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00152', 'Fabian', 'Keener', 'Manston', 16, '76 Hollow Ridge Parkway', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00153', 'Alidia', 'Geertz', 'Reaper', 14, '0 Northridge Road', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00154', 'Davida', 'Carthew', 'Noyes', 16, '4271 Pennsylvania Hill', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00155', 'Myrna', 'Klouz', 'Alenichev', 16, '470 Hintze Hill', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00156', 'Sidonnie', 'Philbrick', 'Andres', 11, '68889 Everett Junction', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00157', 'Annalee', 'Bason', 'Dracey', 16, '4 Starling Hill', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00158', 'Brian', 'Ferrarello', 'Musk', 12, '50713 Warrior Circle', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00159', 'Bethena', 'Rochelle', 'Gue', 11, '744 Vidon Point', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00160', 'Alexi', 'Sapson', 'Northwood', 13, '94 Leroy Street', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00161', 'George', 'Brommage', 'Bourdon', 13, '16 Del Sol Lane', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00162', 'Nessy', 'Saffle', 'Rideout', 15, '0302 Prairie Rose Court', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00163', 'Elliot', 'Iacomelli', 'Sharnock', 11, '4826 David Court', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00164', 'Marijn', 'Oswal', 'Roder', 12, '759 Chive Trail', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00165', 'Florri', 'Yearsley', 'Foffano', 13, '370 American Point', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00166', 'Elinore', 'Weblin', 'Annatt', 15, '69613 Dahle Hill', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00167', 'Maxie', 'Giovanetti', 'Martelet', 14, '37252 Bellgrove Lane', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00168', 'Carola', 'Moss', 'Ganning', 12, '18720 Warner Pass', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00169', 'Ivan', 'Mushawe', 'Burniston', 11, '062 Portage Center', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00170', 'Sibylla', 'Wingeatt', 'Ritchley', 13, '00 Village Green Street', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00171', 'Austine', 'Bolingbroke', 'Seelbach', 15, '2 Anniversary Crossing', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00172', 'Sebastiano', 'Ticehurst', 'Beresfore', 14, '74 Stuart Center', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00173', 'Meghann', 'Poulsum', 'Jane', 16, '453 Bashford Road', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00174', 'Hanna', 'Lain', 'Dibner', 12, '045 Starling Junction', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00175', 'Christye', 'Madle', 'Pittford', 11, '6547 Crowley Court', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00176', 'Sollie', 'Duxbarry', 'Bencher', 15, '900 Oak Valley Park', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00177', 'Missie', 'Rasmus', 'Hinrichs', 14, '861 Dottie Court', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00178', 'Cozmo', 'Austen', 'Malafe', 12, '4094 Kim Crossing', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00179', 'Gabby', 'Bohl', 'Pennick', 12, '223 Corben Way', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00180', 'Zack', 'Jesson', 'Critcher', 13, '6 Farwell Park', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00181', 'Jackie', 'Canas', 'Leyshon', 12, '377 Bartelt Avenue', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00182', 'Thomasina', 'Dalliwater', 'Abazi', 11, '8 Summer Ridge Hill', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00183', 'Shamus', 'Billinge', 'Clopton', 16, '25 Sachs Circle', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00184', 'Kristin', 'Charker', 'Hedley', 14, '36439 Hanson Road', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00185', 'Isadore', 'Quittonden', 'Cambridge', 14, '0374 Oak Crossing', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00186', 'Laurianne', 'Hazlewood', 'Hazeldene', 14, '46165 Macpherson Way', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00187', 'Emlyn', 'Tille', 'Boch', 13, '1641 Autumn Leaf Terrace', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00188', 'Bealle', 'Toe', 'Joul', 12, '472 Ilene Plaza', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00189', 'Yvor', 'Cornick', 'Thowless', 13, '7271 Eagan Junction', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00190', 'Lacy', 'Bolsover', 'Kevern', 16, '973 Butternut Hill', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00191', 'Slade', 'Scrase', 'Jados', 15, '720 Talisman Court', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00192', 'Heloise', 'Castagnaro', 'Bricknall', 15, '5 Arizona Pass', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00193', 'Korey', 'Palffy', 'Pulster', 12, '9042 Kings Lane', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00194', 'Dionne', 'Entres', 'Fadell', 12, '37 Crowley Alley', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00195', 'Jandy', 'Isherwood', 'Brabant', 16, '3288 Riverside Park', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00196', 'Rhoda', 'Fenich', 'Neathway', 12, '18 Blue Bill Park Crossing', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00197', 'Lilllie', 'Starton', 'Gott', 16, '6673 Homewood Pass', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00198', 'Laurence', 'Buddles', 'Richen', 14, '0 Toban Crossing', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00199', 'Kerwin', 'Le Grand', 'Bownd', 15, '79 Blue Bill Park Drive', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00200', 'Ellerey', 'Eastby', 'Kenyam', 15, '067 Montana Point', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00201', 'Bone', 'Goulder', 'Frith', 16, '2 Alpine Street', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00202', 'Calley', 'Bielby', 'Crauford', 11, '78 Vernon Avenue', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00203', 'Dyan', 'Edser', 'Forrest', 12, '364 Sommers Junction', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00204', 'Aggi', 'Shemelt', 'Haibel', 15, '2743 Michigan Avenue', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00205', 'Dreddy', 'Girodin', 'Birdwhistle', 13, '5994 Hovde Court', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00206', 'Sydelle', 'Hayden', 'Waddams', 11, '303 Straubel Park', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00207', 'Charline', 'Levicount', 'Phinn', 12, '4 Northland Park', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00208', 'Marlena', 'Persich', 'Eton', 13, '133 Harbort Point', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00209', 'Agnese', 'Furber', 'Tollit', 11, '5 Washington Plaza', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00210', 'Bendix', 'Leggate', 'Zanetello', 13, '99 Troy Street', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00211', 'Domeniga', 'McGurgan', 'Ruppeli', 14, '9 Spaight Place', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00212', 'Cathleen', 'Searchfield', 'Zellner', 14, '64792 Lighthouse Bay Park', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00213', 'Graham', 'Jindrak', 'Orpen', 14, '4 Loftsgordon Junction', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00214', 'Ax', 'Niemetz', 'Nunns', 11, '76 Esch Way', 9, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00215', 'Elton', 'McRae', 'Brose', 14, '907 8th Road', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00216', 'Bryant', 'Grayshan', 'Bims', 12, '5314 Sunnyside Avenue', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00217', 'Filberte', 'Cobbin', 'Diprose', 12, '2647 Talmadge Center', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00218', 'Stephana', 'Crilly', 'Stamps', 14, '570 Melrose Trail', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00219', 'Hall', 'Yakebovich', 'Goroni', 15, '0004 Elka Hill', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00220', 'Lorettalorna', 'Pulhoster', 'Morey', 11, '6157 Mosinee Lane', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00221', 'Pansy', 'Hurlestone', 'Garmston', 14, '49 Cardinal Street', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00222', 'Land', 'Gosse', 'Pittle', 16, '38 Ilene Terrace', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00223', 'Sibylle', 'Riggert', 'Belhomme', 16, '234 Orin Way', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00224', 'Monika', 'Valde', 'Alam', 13, '9 Melody Road', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00225', 'Breena', 'Middleweek', 'Quibell', 16, '233 Longview Terrace', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00226', 'Dianne', 'Guilloneau', 'Chree', 14, '586 Karstens Lane', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00227', 'Janaye', 'Lepere', 'Asson', 16, '2639 Nova Alley', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00228', 'Muffin', 'Beany', 'Roscamps', 15, '09 Hollow Ridge Street', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00229', 'Hamlin', 'Brakewell', 'Burleton', 11, '5936 Scoville Avenue', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00230', 'Ransom', 'Fiddymont', 'Meanwell', 16, '79514 Bunting Place', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00231', 'Lalo', 'Di Nisco', 'Mileham', 11, '8 Laurel Circle', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00232', 'Jaynell', 'Abrahami', 'Izkovitz', 15, '1141 Sugar Way', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00233', 'Arabel', 'Huntriss', 'Rees', 12, '140 Warrior Drive', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00234', 'Daisie', 'Hartly', 'Ilden', 15, '22 Vera Place', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00235', 'Welby', 'Labitt', 'Fawdrie', 15, '925 Dapin Crossing', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00236', 'Minne', 'Lawie', 'Ballchin', 13, '15 School Circle', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00237', 'Stefa', 'Aldritt', 'Rosell', 11, '4 Schlimgen Street', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00238', 'Daryn', 'Ridge', 'Wickardt', 11, '6609 Hagan Road', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00239', 'Abe', 'Goodlake', 'Mallalieu', 15, '02893 Bunker Hill Road', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00240', 'Philippa', 'Burdin', 'Lennox', 12, '1741 Chive Lane', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00241', 'Karlis', 'Ritzman', 'Thurman', 11, '1028 East Court', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00242', 'Natty', 'Litton', 'Hegges', 15, '9919 Northview Trail', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00243', 'Jesselyn', 'Burghill', 'Fairnington', 15, '7 Melody Lane', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00244', 'Ravid', 'Fairhead', 'McGerraghty', 13, '4 Russell Crossing', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00245', 'Ruthann', 'Camps', 'Ducarne', 11, '880 Gina Court', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00246', 'Doreen', 'Sellwood', 'Tidder', 13, '02766 Kingsford Circle', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00247', 'Cleve', 'Caplin', 'Joannic', 12, '14245 Schurz Drive', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00248', 'Fletch', 'Poag', 'Esbrook', 13, '8608 Westport Parkway', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00249', 'Kerianne', 'Copin', 'Hinckes', 15, '15 Forest Point', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00250', 'Mame', 'Worland', 'Freund', 11, '9 Southridge Street', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00251', 'Tripp', 'Skerm', 'Misselbrook', 16, '9933 Claremont Road', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00252', 'Kipp', 'Briscoe', 'De Biaggi', 15, '78428 Golden Leaf Lane', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00253', 'Sigismondo', 'Egan', 'Gooly', 14, '58719 Sloan Court', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00254', 'Zorina', 'Mariotte', 'Tyrone', 11, '246 Lighthouse Bay Hill', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00255', 'Modesta', 'Nicely', 'Moehle', 13, '02 Anniversary Park', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00256', 'Tom', 'Colbran', 'Mutimer', 13, '694 Buena Vista Crossing', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00257', 'Sibylle', 'Broe', 'Silbersak', 14, '91203 Main Lane', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00258', 'Joyce', 'Folley', 'McRobbie', 16, '6 Hoard Avenue', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00259', 'Monika', 'Scardifield', 'Godspeede', 16, '1 Lunder Circle', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00260', 'Rayner', 'O''Corrin', 'Glasby', 11, '227 Homewood Plaza', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00261', 'Jim', 'Minors', 'Bittlestone', 16, '8416 Bartelt Avenue', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00262', 'Slade', 'Lyst', 'Pawellek', 16, '83358 Sage Way', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00263', 'Vitia', 'Trusse', 'Abazi', 11, '7 Ryan Pass', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00264', 'Dru', 'O''Curran', 'McCord', 11, '05 Northwestern Center', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00265', 'Cherlyn', 'Gutteridge', 'Martynov', 16, '5837 Welch Lane', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00266', 'Carrol', 'Pelosi', 'Boadby', 14, '71 Di Loreto Drive', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00267', 'Jennine', 'Dexter', 'Alfonsini', 15, '9399 Barby Parkway', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00268', 'Suzy', 'Fozard', 'Metzke', 12, '672 Browning Trail', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00269', 'Phedra', 'Calwell', 'Agneau', 15, '96944 Heffernan Lane', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00270', 'Ewen', 'Lintott', 'Faithfull', 13, '3 Barnett Drive', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00271', 'Priscilla', 'Ummfrey', 'Carnoghan', 16, '0188 Sachs Trail', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00272', 'Jammal', 'Scammell', 'Pizer', 14, '42614 Sachs Center', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00273', 'Faunie', 'Whodcoat', 'Alfonso', 12, '026 Division Junction', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00274', 'Peri', 'Blumsom', 'Horstead', 15, '67570 Mcguire Way', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00275', 'Barris', 'Turbefield', 'Hansemann', 15, '617 Fieldstone Junction', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00276', 'Winslow', 'Charley', 'Curston', 14, '879 Waxwing Drive', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00277', 'Eveline', 'Davidsson', 'Gascone', 14, '69 Mosinee Terrace', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00278', 'Oralia', 'Gerretsen', 'de Guise', 16, '1434 La Follette Hill', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00279', 'Allyce', 'Andreu', 'Powrie', 14, '022 Jackson Park', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00280', 'Sigismond', 'Lefwich', 'Botting', 14, '112 Independence Avenue', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00281', 'Bianca', 'Nunns', 'Winckworth', 13, '267 Miller Circle', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00282', 'Elias', 'Crowther', 'Genders', 12, '8 Westridge Place', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00283', 'Trude', 'Dunsire', 'Fownes', 13, '09429 Laurel Center', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00284', 'Tucker', 'Fraulo', 'Brower', 13, '248 Lien Point', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00285', 'Vic', 'Bordman', 'Cockett', 12, '2269 Park Meadow Point', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00286', 'Diahann', 'Watton', 'Trunby', 13, '640 Anniversary Terrace', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00287', 'Emory', 'Neasham', 'Yaknov', 13, '82 Dayton Point', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00288', 'Gery', 'Hyland', 'Fogarty', 16, '35587 Lake View Trail', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00289', 'Philbert', 'Bercher', 'Clemenzo', 13, '73522 Troy Crossing', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00290', 'Gaultiero', 'Pain', 'Quest', 11, '08970 Canary Circle', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00291', 'Rodolph', 'Chislett', 'McCoveney', 11, '795 Jenna Parkway', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00292', 'Basilio', 'McLaughlan', 'Brimicombe', 11, '55917 Hermina Junction', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00293', 'Perle', 'Dolphin', 'Arent', 11, '44 1st Parkway', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00294', 'Immanuel', 'Calderwood', 'Turban', 14, '03332 Chive Parkway', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00295', 'Wakefield', 'Ebenezer', 'Wilcott', 11, '8 Starling Drive', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00296', 'Kylie', 'Dellenbroker', 'Teligin', 13, '0 Dixon Lane', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00297', 'Blythe', 'Brody', 'Clemmett', 12, '8 Monterey Road', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00298', 'Dasi', 'Mantha', 'Lassetter', 16, '19 Browning Terrace', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00299', 'Dyna', 'Killiam', 'Gildroy', 14, '1705 Linden Drive', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00300', 'Alicea', 'Nelius', 'Tasseler', 14, '39 Shasta Parkway', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00301', 'Aron', 'Storm', 'Fearfull', 15, '51 Hazelcrest Center', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00302', 'Bathsheba', 'Malcher', 'Sansam', 13, '56 Memorial Trail', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00303', 'Conant', 'Symers', 'Scimonelli', 11, '3 Westport Point', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00304', 'Hesther', 'Sexstone', 'O''Rudden', 11, '2969 Butterfield Road', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00305', 'Cherish', 'Rabat', 'Mollen', 12, '95 Weeping Birch Circle', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00306', 'Loralyn', 'Bryden', 'Swalwel', 11, '979 Sunfield Trail', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00307', 'Graham', 'Cohani', 'Assinder', 11, '8 Dayton Center', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00308', 'Erminia', 'Danilyuk', 'Epinay', 14, '858 Green Junction', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00309', 'Lionel', 'Gull', 'Petrovsky', 15, '355 Summer Ridge Avenue', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00310', 'Marje', 'Woodyeare', 'MacInherney', 12, '77276 Vernon Terrace', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00311', 'Vachel', 'Maxwell', 'Wraggs', 16, '63413 Sycamore Pass', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00312', 'Shantee', 'Giurio', 'Baudet', 11, '9170 Loomis Trail', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00313', 'Hirsch', 'Menhenitt', 'Trillow', 13, '4101 Lakewood Gardens Junction', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00314', 'Gilbert', 'Tuxsell', 'Healy', 12, '8 Oriole Crossing', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00315', 'Angelo', 'Pullin', 'Rubica', 11, '05 Continental Center', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00316', 'Stormi', 'Bolstridge', 'Morrant', 15, '685 Anhalt Terrace', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00317', 'Briny', 'Ertel', 'Sperrett', 13, '04 Crescent Oaks Hill', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00318', 'Elena', 'McMeanma', 'Corringham', 14, '52688 Almo Center', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00319', 'Donella', 'Bollini', 'Tumbridge', 12, '1170 Graedel Court', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00320', 'Zechariah', 'Stannard', 'Bradtke', 15, '66431 Grasskamp Parkway', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00321', 'Dorelle', 'Heatherington', 'Cawdery', 15, '9453 Lakeland Crossing', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00322', 'Janenna', 'Brugger', 'Middlebrook', 15, '8800 Pine View Alley', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00323', 'Jacques', 'Bramo', 'Batchelor', 12, '0 Carpenter Crossing', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00324', 'Sheila-kathryn', 'Woolfenden', 'Bahls', 12, '60147 Oak Point', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00325', 'Alvy', 'Bettles', 'Hazle', 11, '7127 Dapin Junction', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00326', 'Bastian', 'Trees', 'Tournie', 12, '7 Manufacturers Court', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00327', 'Maria', 'MacPaik', 'Gwyllt', 13, '6 Meadow Vale Way', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00328', 'Brendan', 'Excell', 'Wheadon', 11, '64 Anzinger Road', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00329', 'Rosanne', 'Rome', 'Deetlof', 12, '74840 Manley Point', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00330', 'Tomas', 'Catteroll', 'Utterson', 11, '43325 Heath Point', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00331', 'Isadore', 'Paylor', 'Shakesbye', 12, '0 Huxley Lane', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00332', 'Chev', 'Rablin', 'Chatburn', 14, '2939 Karstens Way', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00333', 'Maiga', 'Giacomasso', 'Lippett', 11, '7733 Boyd Terrace', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00334', 'Shanta', 'Ferrea', 'Buckleigh', 14, '08296 Banding Court', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00335', 'Madalena', 'Cristoferi', 'McFarlane', 12, '69175 Kingsford Hill', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00336', 'Corenda', 'Stegel', 'Giannazzi', 16, '4526 2nd Lane', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00337', 'Lambert', 'Freckleton', 'Sherewood', 11, '7 Shasta Alley', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00338', 'Gisele', 'Laverack', 'Ferney', 14, '45 Ilene Lane', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00339', 'Gage', 'Ailmer', 'Cowe', 14, '9279 Bowman Place', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00340', 'Deirdre', 'Klyn', 'Mathonnet', 13, '49 Kennedy Road', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00341', 'Codi', 'Donaher', 'Gummer', 16, '12 Hooker Plaza', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00342', 'Desdemona', 'Dugood', 'Guite', 13, '2 Main Trail', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00343', 'Katinka', 'Knight', 'Sandey', 13, '12961 Fieldstone Plaza', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00344', 'Olin', 'Josskovitz', 'Bellefonte', 12, '17892 Delaware Terrace', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00345', 'Phyllis', 'Mathelon', 'Barber', 12, '6394 Grim Park', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00346', 'Mariam', 'Frankton', 'Malan', 15, '465 Tennessee Park', 10, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00347', 'Carmella', 'Baylay', 'Goddert.sf', 14, '00 Hoffman Avenue', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00348', 'Gypsy', 'Croson', 'Stitfall', 11, '53892 Dorton Court', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00349', 'Edgar', 'Corcut', 'Rosson', 12, '390 Miller Lane', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00350', 'Sidonnie', 'Breazeall', 'Eivers', 11, '663 Glendale Road', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00351', 'Teodora', 'Grimditch', 'Gagin', 14, '73 Green Court', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00352', 'Blanca', 'Clohissy', 'Emson', 15, '6 Judy Park', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00353', 'Jon', 'Learoid', 'Frusher', 13, '5 Forster Way', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00354', 'Bennett', 'Obray', 'Connachan', 16, '2027 Almo Pass', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00355', 'Wandie', 'Tessyman', 'Cahani', 11, '586 Stone Corner Lane', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00356', 'Riva', 'Droghan', 'Birchenough', 11, '096 Heath Terrace', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00357', 'Alvan', 'Yanshonok', 'Rikel', 14, '96673 Straubel Point', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00358', 'Lily', 'Leigh', 'Faich', 14, '7 Monterey Drive', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00359', 'Jackson', 'Francklin', 'Roubert', 11, '63148 Ridge Oak Road', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00360', 'Madge', 'Skoate', 'Bendelow', 13, '591 Johnson Junction', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00361', 'Teddie', 'Millett', 'Weiner', 12, '3028 Armistice Way', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00362', 'Warner', 'Morland', 'Lightwood', 14, '663 Ryan Crossing', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00363', 'Georgi', 'Davidovich', 'Spenclay', 11, '6 Macpherson Point', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00364', 'Minnnie', 'Jan', 'Wharmby', 15, '93 Sunbrook Way', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00365', 'Eugenius', 'Peskett', 'Lubomirski', 11, '5 Hallows Park', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00366', 'Darline', 'Wickling', 'Gallahar', 14, '92852 Sheridan Pass', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00367', 'Enid', 'Shemwell', 'Krystek', 11, '27097 Kim Parkway', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00368', 'Mylo', 'Bredbury', 'Shurman', 14, '842 Parkside Circle', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00369', 'Linus', 'Wontner', 'Server', 14, '62586 Gerald Road', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00370', 'Jennica', 'Costello', 'Cino', 11, '78585 Spohn Junction', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00371', 'Romy', 'Glenwright', 'Bickerstaffe', 13, '3389 Northland Circle', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00372', 'Gael', 'Kaplin', 'Glennie', 15, '640 Cascade Alley', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00373', 'Hyacintha', 'Guerreiro', 'Faunt', 11, '10847 Delaware Court', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00374', 'Courtney', 'Merrill', 'Phripp', 16, '842 Parkside Terrace', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00375', 'Corrinne', 'de la Valette Parisot', 'Hutchcraft', 15, '128 Lien Way', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00376', 'Jeannette', 'Grogono', 'Royl', 11, '6 Ramsey Avenue', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00377', 'Augustine', 'Ziehm', 'Maruska', 16, '0 Packers Point', 7, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00378', 'Cara', 'Bromhead', 'Buney', 14, '9984 Havey Road', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00379', 'Franklyn', 'Manvell', 'Sotham', 14, '90 Farmco Street', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00380', 'Antonia', 'Sainsbury', 'Gilfether', 14, '06586 Buhler Alley', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00381', 'Arlene', 'Tofpik', 'Eastridge', 15, '930 Lighthouse Bay Center', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00382', 'Hedvige', 'Liven', 'Sudell', 11, '09 Dovetail Hill', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00383', 'Jody', 'Ferry', 'Pierrepont', 14, '105 Canary Court', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00384', 'Kris', 'Burchnall', 'Caldecourt', 11, '09 Lerdahl Way', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00385', 'Celle', 'Clilverd', 'Bushrod', 14, '93294 Transport Court', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00386', 'Bryn', 'Huccaby', 'Kirkup', 15, '15 Golf View Point', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00387', 'Kasper', 'Dunsmore', 'Stanmore', 13, '44634 1st Crossing', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00388', 'Karia', 'Hughesdon', 'Dunmore', 12, '98244 Fair Oaks Terrace', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00389', 'Jessi', 'Sonschein', 'Moralee', 15, '05625 Marquette Alley', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00390', 'Wes', 'Wyant', 'Biaggiotti', 12, '06 Wayridge Pass', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00391', 'Ray', 'Diaper', 'Gownge', 15, '2324 Leroy Park', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00392', 'Halie', 'Francescotti', 'Bodega', 16, '0 Dapin Hill', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00393', 'Horten', 'Geeritz', 'Deathridge', 14, '65 Nobel Alley', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00394', 'Sue', 'Anfonsi', 'Goodnow', 14, '05544 Graceland Circle', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00395', 'Lil', 'Meneo', 'Cuniam', 11, '30 Mariners Cove Lane', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00396', 'Katalin', 'Alvares', 'Aggott', 13, '68 Old Gate Center', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00397', 'Antonin', 'Eunson', 'Kestin', 11, '482 Sheridan Parkway', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00398', 'Eula', 'Tooley', 'Medforth', 11, '92 Armistice Crossing', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00399', 'Dareen', 'Witsey', 'Duval', 14, '32204 Fisk Drive', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00400', 'Jackelyn', 'Di Giorgio', 'Spira', 12, '602 Marquette Point', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00401', 'Karon', 'Hegg', 'Addenbrooke', 14, '35273 Mosinee Alley', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00402', 'Allyson', 'Hawkeridge', 'Epple', 11, '73658 Riverside Junction', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00403', 'Cyrill', 'Aspinall', 'Ruddin', 15, '26773 Mcbride Hill', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00404', 'Jamil', 'Dunphy', 'Amthor', 11, '863 Fuller Trail', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00405', 'Beau', 'Lipscomb', 'Trowl', 16, '3565 Pine View Hill', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00406', 'Frankie', 'Redfearn', 'Serridge', 13, '7 Hintze Lane', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00407', 'Tedman', 'Gringley', 'Beazey', 16, '3390 Katie Terrace', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00408', 'Yanaton', 'Redsull', 'Kingsnoad', 15, '4 Hollow Ridge Street', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00409', 'Weston', 'Magenny', 'Stitfall', 14, '526 Anniversary Parkway', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00410', 'Gael', 'Gaspard', 'Scirman', 11, '64 Old Gate Junction', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00411', 'Korney', 'Peppard', 'Willson', 11, '79092 Eggendart Center', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00412', 'Godart', 'Bollom', 'Burress', 16, '07056 Nancy Parkway', 8, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00413', 'Nonnah', 'Felgat', 'McConnachie', 15, '51846 Prentice Road', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00414', 'Jaclyn', 'Meddings', 'De L''Isle', 13, '42 Johnson Avenue', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00415', 'Niall', 'Collibear', 'Rawsthorne', 14, '0188 Algoma Way', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00416', 'Reginauld', 'Tett', 'Lengthorn', 11, '46987 Petterle Pass', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00417', 'Cyrille', 'Stennard', 'Soden', 15, '59310 Merchant Pass', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00418', 'Agata', 'Khrishtafovich', 'Antonias', 13, '1607 North Park', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00419', 'Jeanne', 'Leyburn', 'Fidler', 11, '15027 Del Mar Court', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00420', 'Nestor', 'Anney', 'Minghetti', 14, '926 Brentwood Point', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00421', 'Averil', 'Trott', 'Oblein', 16, '01749 Pennsylvania Parkway', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00422', 'Tymothy', 'Satcher', 'McCrossan', 15, '148 Harbort Lane', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00423', 'Zonda', 'Eisenberg', 'Flucker', 15, '57 Manley Park', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00424', 'Addy', 'Dominguez', 'Ference', 12, '9 Express Road', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00425', 'Huntlee', 'Fillery', 'Du Plantier', 14, '1 Westridge Place', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00426', 'Ludvig', 'Clissett', 'Canto', 11, '3694 Transport Hill', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00427', 'Jacquette', 'McGloughlin', 'Dignam', 16, '4 Lerdahl Alley', 10, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00428', 'Celestyna', 'Mineghelli', 'Ovenden', 16, '63801 Prairie Rose Center', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00429', 'Celle', 'O''Leagham', 'Landreth', 15, '5 Pierstorff Place', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00430', 'Fabien', 'Ziemen', 'Daw', 12, '0 Merchant Lane', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00431', 'Barbara', 'Beere', 'McMorran', 16, '3491 Darwin Point', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00432', 'Rowney', 'Cuthbert', 'Lindores', 16, '8773 Debs Way', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00433', 'Abel', 'Wynes', 'Jefferd', 11, '14012 Graedel Avenue', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00434', 'Zeke', 'Kissock', 'Jarnell', 14, '61 Utah Junction', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00435', 'Gisele', 'Durrad', 'Worshall', 11, '9 Hooker Parkway', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00436', 'Amos', 'Edger', 'Delhay', 14, '9146 Evergreen Junction', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00437', 'Ana', 'McNeill', 'Brunetti', 14, '4981 Swallow Street', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00438', 'Bastian', 'Vanns', 'Wethered', 12, '52 Evergreen Plaza', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00439', 'Jeane', 'Sprague', 'Gerry', 15, '8 Upham Road', 9, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00440', 'Brittany', 'Allsobrook', 'Maclaine', 11, '0 Miller Drive', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00441', 'Sharleen', 'Jimenez', 'Wase', 11, '9 Golf View Crossing', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00442', 'Oates', 'Hurler', 'Jacobssen', 11, '7 Vermont Drive', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00443', 'Norby', 'Keeley', 'Sharkey', 15, '6 Acker Court', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00444', 'Cale', 'Zanazzi', 'Scutchings', 14, '36839 Haas Place', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00445', 'Davis', 'Chestnutt', 'Lambertson', 13, '1601 Di Loreto Point', 9, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00446', 'Alwyn', 'Surman', 'Sivior', 11, '1328 Sunnyside Lane', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00447', 'Yard', 'Bank', 'Fandrich', 15, '52 Little Fleur Plaza', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00448', 'Averil', 'Wye', 'Elie', 13, '18 Leroy Street', 8, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00449', 'Aylmar', 'Bellringer', 'McLorinan', 16, '087 Towne Court', 7, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00450', 'Nanny', 'Aronoff', 'Feaviour', 15, '53 Upham Hill', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00451', 'Leupold', 'Hatto', 'Docker', 12, '80 7th Drive', 10, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00452', 'Jeremie', 'Neighbour', 'Gulliver', 12, '7 Independence Circle', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00453', 'Shalne', 'Vaugham', 'Dumbellow', 11, '6627 Pine View Road', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00454', 'Fletch', 'Steptoe', 'Reiner', 14, '165 Harbort Junction', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00455', 'Ettie', 'McMaster', 'Fiddler', 14, '8 Towne Street', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00456', 'Ynez', 'Marran', 'Burgwyn', 12, '349 Gerald Drive', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00457', 'Sorcha', 'Harvatt', 'Klimp', 13, '95 Kedzie Park', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00458', 'Sayers', 'Ratledge', 'Bernard', 11, '9 New Castle Crossing', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00459', 'Doralynne', 'Lante', 'Platt', 13, '1229 Mitchell Road', 8, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00460', 'Corrina', 'Haill', 'Croysdale', 14, '91 Anhalt Alley', 8, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00461', 'Kaitlynn', 'Philp', 'Mayoral', 11, '100 Ludington Circle', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00462', 'Addy', 'Ivakin', 'Grimsey', 16, '360 Vahlen Center', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00463', 'Timi', 'Drover', 'Keford', 16, '16299 Cardinal Parkway', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00464', 'Mirabel', 'Gillham', 'Steely', 15, '9224 Jackson Center', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00465', 'Jeri', 'Bagworth', 'Drance', 12, '12438 Oneill Center', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00466', 'Shelba', 'Giddy', 'Blatherwick', 11, '808 Moose Terrace', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00467', 'Leilah', 'Spacey', 'Tight', 13, '16 Hovde Way', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00468', 'Anatollo', 'Giacomelli', 'Eadington', 14, '86308 Hintze Crossing', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00469', 'Peria', 'Daburn', 'Aird', 11, '22 1st Alley', 8, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00470', 'Bail', 'Aleavy', 'Gooble', 12, '8385 Sloan Lane', 7, 'Non-binary');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00471', 'Gypsy', 'Bradnock', 'Hornung', 16, '45751 Loeprich Point', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00472', 'Kingston', 'Peacham', 'Causon', 11, '156 Fallview Drive', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00473', 'Nikos', 'McRannell', 'Test', 15, '61 Prairieview Drive', 9, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00474', 'Sigrid', 'Spelwood', 'Ondrousek', 11, '4178 Kenwood Park', 9, 'Female');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00475', 'Denna', 'Corradengo', 'Wragge', 14, '11 Havey Alley', 7, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00476', 'Chickie', 'Daniele', 'Reddel', 14, '9 Dapin Terrace', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00477', 'Wynn', 'Beslier', 'Zavattari', 13, '947 Monica Terrace', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00478', 'Quintana', 'Tanzig', 'Beaudry', 14, '53 Kinsman Road', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00479', 'Hewett', 'Mowett', 'Smillie', 15, '9 Eastwood Circle', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00480', 'Scotty', 'Rohloff', 'Di Domenico', 16, '85833 Cardinal Terrace', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00481', 'Peggie', 'Erratt', 'Malam', 11, '35895 Scoville Crossing', 7, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00482', 'Wolfie', 'Wynes', 'Winterflood', 11, '59295 Melrose Place', 10, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00483', 'Ingar', 'Cavilla', 'Anstey', 12, '1 Meadow Vale Street', 10, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00484', 'Cristiano', 'Reyes', 'Boutton', 11, '22893 Trailsway Crossing', 10, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00485', 'Orv', 'Jedrzejczak', 'Benterman', 14, '43646 La Follette Junction', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00486', 'Irvine', 'Idwal Evans', 'Pirri', 14, '70735 Homewood Way', 9, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00487', 'Berky', 'Zuenelli', 'Boutton', 14, '652 Erie Junction', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00488', 'Saidee', 'Dionisi', 'Load', 11, '1466 Lillian Terrace', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00489', 'Gabriell', 'Ingarfill', 'Jansson', 15, '56 Huxley Drive', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00490', 'Mikkel', 'Urlich', 'Clery', 14, '2768 Lakewood Road', 7, 'Bigender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00491', 'Layton', 'Playhill', 'Sterzaker', 16, '2 Kensington Drive', 9, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00492', 'Evelina', 'Spellacy', 'Fortnam', 13, '2 Cherokee Plaza', 8, 'Agender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00493', 'Deborah', 'Lortz', 'Polon', 14, '0342 Arkansas Terrace', 8, 'Genderqueer');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00494', 'Northrup', 'Carbonell', 'Cristofol', 12, '379 Stoughton Parkway', 10, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00495', 'Fania', 'Hallihan', 'Rebichon', 15, '2 David Alley', 10, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00496', 'Justinn', 'Reston', 'Sellman', 12, '65 Jana Parkway', 9, 'Polygender');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00497', 'Delilah', 'Meecher', 'Ellit', 16, '44 Surrey Alley', 8, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00498', 'Elsi', 'Shaul', 'Stirton', 15, '65 Memorial Alley', 7, 'Genderfluid');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00499', 'Hyman', 'Cholonin', 'Bugge', 11, '744 Cherokee Hill', 7, 'Male');
insert into STUDENTS (student_id, first_name, middle_initial, last_name, age, address, grade, gender) values ('S00500', 'Timmy', 'Widdison', 'Molen', 12, '179 Loomis Pass', 10, 'Bigender');
